(() => {
  'use strict';
  const STORAGE_KEY = 'sensei-jitan-v12-tests';
  const state = { page: 'home', returnPage: 'home', grade: '5年', subject: '算数', publisher: '東京書籍', unit: '割合', level: '標準', result: null, worksheetResult: null, activeTab: 'overview', lessonMinutes: 45 };
  const app = document.getElementById('app');
  const subjects = ['国語', '算数', '理科', '社会', '英語'];
  const units = { 国語: ['物語文の読み取り', '漢字の広場', '説明文の要旨'], 算数: ['割合', '小数のかけ算', '図形の面積'], 理科: ['天気の変化', '植物の発芽', '電流がつくる磁力'], 社会: ['日本の国土', '食料生産', '工業生産'], 英語: ['自己紹介', '道案内', 'ものの名前'] };
  const levels = ['やさしい', '標準', 'チャレンジ', '特別支援配慮'];
  const gradeOptions = ['1年', '2年', '3年', '4年', '5年', '6年'];
  const publishers = ['東京書籍', '大日本図書', '学校図書', '教育出版', '啓林館', '日本文教出版'];
  const textbookUnits = {
    '5年|算数|東京書籍': ['整数と小数', '直方体や立方体の体積', '比例', '小数のかけ算', '小数のわり算', '合同な図形', '図形の角', '偶数と奇数・倍数と約数', '分数と小数・整数の関係', '分数のたし算とひき算', '平均', '単位量あたりの大きさ', '四角形と三角形の面積', '割合', '帯グラフと円グラフ', '変わり方調べ', '正多角形と円周の長さ', '角柱と円柱'],
    '5年|算数|大日本図書': ['整数と小数', '体積', '小数のかけ算', '小数のわり算', '合同な図形', '図形の角', '偶数と奇数・倍数と約数', '分数と小数', '分数のたし算とひき算', '平均', '単位量あたりの大きさ', '図形の面積', '割合', '帯グラフと円グラフ', '変わり方', '正多角形と円周', '角柱と円柱'],
    '5年|算数|学校図書': ['整数と小数', '体積', '小数のかけ算', '小数のわり算', '合同な図形', '図形の角', '倍数と約数', '分数', '平均', '単位量あたりの大きさ', '図形の面積', '割合', '帯グラフと円グラフ', '変わり方', '正多角形と円周', '角柱と円柱'],
    '5年|算数|教育出版': ['整数と小数', '体積', '小数のかけ算', '小数のわり算', '合同な図形', '図形の角', '倍数と約数', '分数のたし算とひき算', '平均', '単位量あたりの大きさ', '図形の面積', '割合', '帯グラフと円グラフ', '変わり方', '正多角形と円周', '角柱と円柱'],
    '5年|算数|啓林館': ['整数と小数', '体積', '比例', '小数のかけ算', '小数のわり算', '合同な図形', '図形の角', '整数の性質', '分数のたし算とひき算', '平均', '単位量あたりの大きさ', '図形の面積', '割合', '帯グラフと円グラフ', '変わり方', '正多角形と円周', '角柱と円柱'],
    '5年|算数|日本文教出版': ['整数と小数', '体積', '小数のかけ算', '小数のわり算', '合同な図形', '図形の角', '整数の性質', '分数', '平均', '単位量あたりの大きさ', '図形の面積', '割合', '帯グラフと円グラフ', '変わり方', '正多角形と円周', '角柱と円柱'],
    '1年|算数|東京書籍': ['なかまづくりとかず', 'なんばんめ', 'どちらがながい', 'いくつといくつ', 'あわせていくつ ふえるといくつ', 'のこりはいくつ ちがいはいくつ', '10よりおおきいかず', 'なんじ なんぷん', 'かたちあそび', 'たしざん', 'ひきざん', 'かずしらべ', 'くらべかた', '1ねんのふくしゅう'],
    '1年|算数|大日本図書': ['なかまづくりとかず', 'なんばんめ', 'どちらがながい', 'いくつといくつ', 'あわせていくつ ふえるといくつ', 'のこりはいくつ ちがいはいくつ', '10よりおおきいかず', 'なんじ なんぷん', 'かたちあそび', 'たしざん', 'ひきざん', 'かずしらべ', 'くらべかた', '1ねんのふくしゅう'],
    '1年|算数|学校図書': ['なかまづくりとかず', 'なんばんめ', 'どちらがながい', 'いくつといくつ', 'たしざん', 'ひきざん', '10よりおおきいかず', 'なんじ なんぷん', 'かたちあそび', 'かずしらべ', 'くらべかた', '1ねんのふくしゅう'],
    '1年|算数|教育出版': ['かずとすうじ', 'なんばんめ', 'どちらがながい', 'いくつといくつ', 'あわせていくつ ふえるといくつ', 'のこりはいくつ ちがいはいくつ', '10よりおおきいかず', 'なんじ なんぷん', 'かたちあそび', 'たしざん', 'ひきざん', 'かずしらべ', 'くらべかた', '1ねんのふくしゅう'],
    '1年|算数|啓林館': ['なかまづくりとかず', 'なんばんめ', 'どちらがながい', 'いくつといくつ', 'あわせていくつ ふえるといくつ', 'のこりはいくつ ちがいはいくつ', '10よりおおきいかず', 'なんじ なんぷん', 'かたちあそび', 'たしざん', 'ひきざん', 'かずしらべ', 'くらべかた', '1ねんのふくしゅう'],
    '1年|算数|日本文教出版': ['なかまづくりとかず', 'なんばんめ', 'どちらがながい', 'いくつといくつ', 'たしざん', 'ひきざん', '10よりおおきいかず', 'なんじ なんぷん', 'かたちあそび', 'かずしらべ', 'くらべかた', '1ねんのふくしゅう'],
    '2年|算数|東京書籍': ['2年のふくしゅう', 'たし算のひっ算', 'ひき算のひっ算', '長さのたんい', '1000までの数', 'かさのたんい', '時こくと時間', '水のかさのたんい', '三角形と四角形', 'かけ算', '九九のきまり', '10000までの数', '長いものの長さのたんい', '分数', 'はこの形', '2年のふくしゅう'],
    '2年|算数|大日本図書': ['2年のふくしゅう', 'たし算のひっ算', 'ひき算のひっ算', '長さ', '1000までの数', 'かさ', '時こくと時間', '三角形と四角形', 'かけ算', '九九のきまり', '10000までの数', '分数', 'はこの形', '2年のふくしゅう'],
    '2年|算数|学校図書': ['2年のふくしゅう', 'たし算とひき算のひっ算', '長さ', '1000までの数', 'かさ', '時こくと時間', '三角形と四角形', 'かけ算', '九九のきまり', '10000までの数', '分数', 'はこの形', '2年のふくしゅう'],
    '2年|算数|教育出版': ['2年のふくしゅう', 'たし算のひっ算', 'ひき算のひっ算', '長さのたんい', '1000までの数', 'かさのたんい', '時こくと時間', '三角形と四角形', 'かけ算', '九九のきまり', '10000までの数', '分数', 'はこの形', '2年のふくしゅう'],
    '2年|算数|啓林館': ['2年のふくしゅう', 'たし算のひっ算', 'ひき算のひっ算', '長さ', '1000までの数', 'かさ', '時こくと時間', '三角形と四角形', 'かけ算', '九九のきまり', '10000までの数', '分数', 'はこの形', '2年のふくしゅう'],
    '2年|算数|日本文教出版': ['2年のふくしゅう', 'たし算のひっ算', 'ひき算のひっ算', '長さ', '1000までの数', 'かさ', '時こくと時間', '三角形と四角形', 'かけ算', '九九のきまり', '10000までの数', '分数', 'はこの形', '2年のふくしゅう'],
    '3年|算数|東京書籍': ['3年のふくしゅう', 'かけ算のきまり', 'わり算', 'たし算とひき算の筆算', '時こくと時間', '長さ', '表とグラフ', 'あまりのあるわり算', '円と球', '小数', '重さ', '分数', '三角形と角', 'ぼうグラフと表', 'そろばん', '3年のふくしゅう'],
    '3年|算数|大日本図書': ['3年のふくしゅう', 'かけ算のきまり', 'わり算', 'たし算とひき算の筆算', '時こくと時間', '長さ', '表とグラフ', 'あまりのあるわり算', '円と球', '小数', '重さ', '分数', '三角形と角', 'ぼうグラフ', 'そろばん', '3年のふくしゅう'],
    '3年|算数|学校図書': ['3年のふくしゅう', 'かけ算', 'わり算', '筆算', '時こくと時間', '長さ', '表とグラフ', 'あまりのあるわり算', '円と球', '小数', '重さ', '分数', '三角形と角', 'ぼうグラフ', 'そろばん', '3年のふくしゅう'],
    '3年|算数|教育出版': ['3年のふくしゅう', 'かけ算のきまり', 'わり算', 'たし算とひき算の筆算', '時こくと時間', '長さ', '表とグラフ', 'あまりのあるわり算', '円と球', '小数', '重さ', '分数', '三角形と角', 'ぼうグラフと表', 'そろばん', '3年のふくしゅう'],
    '3年|算数|啓林館': ['3年のふくしゅう', 'かけ算のきまり', 'わり算', 'たし算とひき算の筆算', '時こくと時間', '長さ', '表とグラフ', 'あまりのあるわり算', '円と球', '小数', '重さ', '分数', '三角形と角', 'ぼうグラフと表', 'そろばん', '3年のふくしゅう'],
    '3年|算数|日本文教出版': ['3年のふくしゅう', 'かけ算のきまり', 'わり算', 'たし算とひき算の筆算', '時こくと時間', '長さ', '表とグラフ', 'あまりのあるわり算', '円と球', '小数', '重さ', '分数', '三角形と角', 'ぼうグラフと表', 'そろばん', '3年のふくしゅう'],
    '4年|算数|東京書籍': ['4年のふくしゅう', '大きな数', '折れ線グラフと表', 'わり算の筆算', '角の大きさ', '垂直・平行と四角形', '小数のしくみ', '式と計算', '面積', '小数のかけ算とわり算', 'がい数', '分数', '変わり方調べ', '直方体と立方体', 'そろばん', '4年のふくしゅう'],
    '4年|算数|大日本図書': ['4年のふくしゅう', '大きな数', '折れ線グラフ', 'わり算の筆算', '角の大きさ', '垂直・平行と四角形', '小数のしくみ', '式と計算', '面積', '小数のかけ算とわり算', 'がい数', '分数', '変わり方', '直方体と立方体', 'そろばん', '4年のふくしゅう'],
    '4年|算数|学校図書': ['4年のふくしゅう', '大きな数', '折れ線グラフと表', 'わり算の筆算', '角の大きさ', '垂直・平行と四角形', '小数', '式と計算', '面積', '小数のかけ算とわり算', 'がい数', '分数', '変わり方', '直方体と立方体', 'そろばん', '4年のふくしゅう'],
    '4年|算数|教育出版': ['4年のふくしゅう', '大きな数', '折れ線グラフと表', 'わり算の筆算', '角の大きさ', '垂直・平行と四角形', '小数のしくみ', '式と計算', '面積', '小数のかけ算とわり算', 'がい数', '分数', '変わり方調べ', '直方体と立方体', 'そろばん', '4年のふくしゅう'],
    '4年|算数|啓林館': ['4年のふくしゅう', '大きな数', '折れ線グラフと表', 'わり算の筆算', '角の大きさ', '垂直・平行と四角形', '小数のしくみ', '式と計算', '面積', '小数のかけ算とわり算', 'がい数', '分数', '変わり方調べ', '直方体と立方体', 'そろばん', '4年のふくしゅう'],
    '4年|算数|日本文教出版': ['4年のふくしゅう', '大きな数', '折れ線グラフと表', 'わり算の筆算', '角の大きさ', '垂直・平行と四角形', '小数のしくみ', '式と計算', '面積', '小数のかけ算とわり算', 'がい数', '分数', '変わり方調べ', '直方体と立方体', 'そろばん', '4年のふくしゅう'],
    '6年|算数|東京書籍': ['6年のふくしゅう', '対称な図形', '文字と式', '分数のかけ算', '分数のわり算', '円の面積', '立体の体積', '比とその利用', '拡大図と縮図', '速さ', '比例と反比例', 'データの調べ方', '場合の数', '図形の見方・考え方', '算数のまとめ', '中学校へのかけ橋'],
    '6年|算数|大日本図書': ['6年のふくしゅう', '対称な図形', '文字と式', '分数のかけ算', '分数のわり算', '円の面積', '立体の体積', '比とその利用', '拡大図と縮図', '速さ', '比例と反比例', 'データの調べ方', '場合の数', '算数のまとめ', '中学校へのかけ橋'],
    '6年|算数|学校図書': ['6年のふくしゅう', '対称な図形', '文字と式', '分数のかけ算とわり算', '円の面積', '立体の体積', '比とその利用', '拡大図と縮図', '速さ', '比例と反比例', 'データの調べ方', '場合の数', '算数のまとめ', '中学校へのかけ橋'],
    '6年|算数|教育出版': ['6年のふくしゅう', '対称な図形', '文字と式', '分数のかけ算', '分数のわり算', '円の面積', '立体の体積', '比とその利用', '拡大図と縮図', '速さ', '比例と反比例', 'データの調べ方', '場合の数', '算数のまとめ', '中学校へのかけ橋'],
    '6年|算数|啓林館': ['6年のふくしゅう', '対称な図形', '文字と式', '分数のかけ算', '分数のわり算', '円の面積', '立体の体積', '比とその利用', '拡大図と縮図', '速さ', '比例と反比例', 'データの調べ方', '場合の数', '算数のまとめ', '中学校へのかけ橋'],
    '6年|算数|日本文教出版': ['6年のふくしゅう', '対称な図形', '文字と式', '分数のかけ算', '分数のわり算', '円の面積', '立体の体積', '比とその利用', '拡大図と縮図', '速さ', '比例と反比例', 'データの調べ方', '場合の数', '算数のまとめ', '中学校へのかけ橋']
  };
  function selectedUnits(){ return textbookUnits[`${state.grade}|${state.subject}|${state.publisher}`] || units[state.subject]; }
  const researchBasis = '<div class="test-source-links"><strong>出題の参考（公開教材の構成を参考にした類題）</strong><div><a href="https://surapuri.jp/elementary_school05/wariai/" target="_blank" rel="noopener">すらぷり</a><a href="https://happylilac.net/keisan-wariai.html" target="_blank" rel="noopener">ちびむすドリル</a><a href="https://www.print365.net/kurabekatabunsyo5nen/" target="_blank" rel="noopener">ぷりんと365</a><a href="https://www.mext.go.jp/component/a_menu/education/micro_detail/__icsFiles/afieldfile/2009/06/16/1234931_004_1.pdf" target="_blank" rel="noopener">文部科学省</a></div></div>';
  const testSets = {
    '5年|算数|割合': [
      { format: '選択式', question: '120円の20%はいくらですか。', choices: ['12円', '24円', '60円', '100円'], answer: '24円', explain: '20%は100分の20です。120×0.2＝24なので、24円です。' },
      { format: '短答', question: '45人のうち女子が18人でした。女子は全体の何%ですか。', answer: '40%', explain: '18÷45＝0.4。0.4を百分率にすると40%です。' },
      { format: '説明問題', question: '定価800円の30%引きの値段を求める方法を説明しましょう。', answer: '800×(1−0.3)＝560円', explain: '30%引きは、もとの70%の値段になるという意味です。800×0.7で560円です。' },
      { format: '選択式', question: 'もとにする量が50、比べる量が15のとき、割合はどれですか。', choices: ['15%', '30%', '50%', '65%'], answer: '30%', explain: '割合は比べる量÷もとにする量。15÷50＝0.3なので30%です。' },
      { format: '短答', question: 'ある数の25%が10です。ある数はいくつですか。', answer: '40', explain: '25%は0.25なので、10÷0.25＝40です。' }
    ]
  };
  const genericTemplates = {
    国語: [{format:'短答',question:'文章の大事な内容を一文でまとめるとき、何に注目しますか。',answer:'中心となる話題と筆者の考え',explain:'くり返し出てくる言葉や段落の中心を探すと、要点を見つけやすくなります。'},{format:'選択式',question:'段落の役割として近いものを選びましょう。',choices:['話題を示す','計算する','地図を読む','実験する'],answer:'話題を示す',explain:'最初の段落には、これから何について書くかを示す役割があります。'}],
    算数: [{format:'短答',question:'この単元で使う大切な式を書きましょう。',answer:'比べる量÷もとにする量＝割合',explain:'割合は、比べる量がもとにする量のどれだけかを表します。'},{format:'選択式',question:'答えを確かめるときに大切なことはどれですか。',choices:['単位や大きさを見る','色だけを見る','速く書く','答えを隠す'],answer:'単位や大きさを見る',explain:'単位や答えの大きさが問題に合っているか確かめます。'}],
    理科: [{format:'選択式',question:'観察するときに記録するとよいものはどれですか。',choices:['日時や変化','好きな色だけ','友達の名前だけ','予想しない'],answer:'日時や変化',explain:'日時と変化を記録すると、結果を比べて考えられます。'},{format:'説明問題',question:'予想を立ててから実験するよさを説明しましょう。',answer:'結果を予想と比べて考えられること',explain:'予想と結果の違いに目を向けると、きまりを見つけやすくなります。'}],
    社会: [{format:'短答',question:'地図で方位を表す基本の4方向を書きましょう。',answer:'東・西・南・北',explain:'地図では方位を使うと、場所の関係を正確に表せます。'},{format:'選択式',question:'資料を読むとき最初に確かめるものはどれですか。',choices:['題名や単位','色の好み','紙の大きさ','文字の形'],answer:'題名や単位',explain:'題名と単位を確かめると、資料が何を表すか分かります。'}],
    英語: [{format:'短答',question:'「私は〜です」と自己紹介するときの表現を書きましょう。',answer:'I am 〜.',explain:'I amは「私は〜です」という意味の表現です。'}]
  };
  function el(selector){ return document.querySelector(selector); }
  function renderHome(){ app.innerHTML = `<section class="hero"><div class="eyebrow">SCHOOLPILOT</div><h1>今日は何を準備しますか？</h1><p>学年と教科を選ぶだけで、授業準備に使える素材をすぐに作れます。</p></section><div class="section-title"><h2>学年を選ぶ</h2><p>まずは対象学年を選択</p></div><div class="grade-grid">${gradeOptions.map(g=>`<button class="choice ${g===state.grade?'selected':''}" data-grade="${g}"><strong>${g}</strong><span>授業素材を探す</span></button>`).join('')}</div><div class="section-title"><h2>教科を選ぶ</h2><p>${state.grade}の単元</p></div><div class="subject-grid">${subjects.map(s=>`<button class="choice ${s===state.subject?'selected':''}" data-subject="${s}"><strong>${s}</strong><span>${units[s].length}単元</span></button>`).join('')}</div><div class="section-title"><h2>単元を選ぶ</h2><p>単元詳細から素材を使えます</p></div><div class="unit-grid">${units[state.subject].map(u=>`<button class="unit-card" data-unit="${u}"><strong>${u}</strong><span>授業案・板書・小テスト・復習テスト</span></button>`).join('')}</div>`; }
  function renderHome(){ app.innerHTML = `<section class="hero"><div class="eyebrow">SCHOOLPILOT</div><h1>授業準備教材を探す</h1><p>学年・教科・教科書出版社を選ぶと、対応する単元を表示します。</p></section><div class="section-title"><h2>学年を選ぶ</h2></div><div class="grade-grid">${gradeOptions.map(g=>`<button class="choice ${g===state.grade?'selected':''}" data-grade="${g}"><strong>${g}</strong></button>`).join('')}</div><div class="section-title"><h2>教科を選ぶ</h2></div><div class="subject-grid">${subjects.map(s=>`<button class="choice ${s===state.subject?'selected':''}" data-subject="${s}"><strong>${s}</strong></button>`).join('')}</div><div class="section-title"><h2>教科書の出版社を選ぶ</h2><p>${state.grade}・${state.subject}</p></div><div class="publisher-grid">${publishers.map(p=>`<button class="choice ${p===state.publisher?'selected':''}" data-publisher="${p}"><strong>${p}</strong></button>`).join('')}</div><p class="publisher-note">単元一覧は、文部科学省の教科書制度および各出版社の公開資料を参考に同梱しています。学校の採択版・年度によって配列や名称が異なる場合があります。</p><div class="section-title"><h2>単元を選ぶ</h2><p>${state.publisher}の公開単元配列を参考</p></div><div class="unit-grid">${selectedUnits().map(u=>`<button class="unit-card" data-unit="${u}"><strong>${u}</strong></button>`).join('')}</div>`; }
  function renderHome(){ const unitList=selectedUnits(); const ready=Boolean(state.grade&&state.subject&&state.publisher&&state.unit); app.innerHTML = `<section class="hero"><div class="eyebrow">SCHOOLPILOT</div><h1>授業準備教材を探す</h1><p>学年・教科・教科書出版社・単元を選んでください。</p></section><div class="section-title"><h2>学年を選ぶ</h2></div><div class="grade-grid">${gradeOptions.map(g=>`<button class="choice ${g===state.grade?'selected':''}" data-grade="${g}"><strong>${g}</strong></button>`).join('')}</div><div class="section-title"><h2>教科を選ぶ</h2></div><div class="subject-grid">${subjects.map(s=>`<button class="choice ${s===state.subject?'selected':''}" data-subject="${s}"><strong>${s}</strong></button>`).join('')}</div><div class="section-title"><h2>教科書の出版社を選ぶ</h2><p>${state.grade}・${state.subject}</p></div><div class="publisher-grid">${publishers.map(p=>`<button class="choice ${p===state.publisher?'selected':''}" data-publisher="${p}"><strong>${p}</strong></button>`).join('')}</div><p class="publisher-note">単元一覧は、文部科学省の教科書制度および各出版社の公開資料を参考に同梱しています。学校の採択版・年度によって配列や名称が異なる場合があります。</p><div class="section-title"><h2>単元を選ぶ</h2><p>${state.publisher}の公開単元配列を参考</p></div><div class="unit-grid">${unitList.map(u=>`<button class="unit-card ${u===state.unit?'selected':''}" data-unit="${u}"><strong>${u}</strong></button>`).join('')}</div><div class="home-search"><button class="primary search-button" data-search ${ready?'':'disabled'}>検索</button>${ready?'':'<p class="search-note">学年・教科・出版社・単元をすべて選択してください。</p>'}</div>`; }
  function loadReviewSaved(){ try{return JSON.parse(localStorage.getItem('schoolpilot-review-tests')||'[]');}catch(e){return [];} }
  function loadSupportSaved(){ try{return JSON.parse(localStorage.getItem('schoolpilot-support-materials')||'[]');}catch(e){return [];} }
  function renderDesk(){ const tests=loadSaved(), reviews=loadReviewSaved(); const cards=(items,kind,offset,store)=>items.map((x,i)=>`<article class="desk-card"><h3>${x.title||`${x.grade} ${x.subject}「${x.unit}」`}</h3><p>${kind} / ${x.level} / ${x.items.length}問</p><div class="actions"><button class="secondary" data-open-saved="${offset+i}" data-open-store="${store}" style="margin-top:12px">元のデータを開く</button><button class="secondary" data-rename-saved="${i}" data-rename-store="${store}" style="margin-top:12px">名前変更</button><button class="danger" data-delete-saved="${i}" data-delete-store="${store}" style="margin-top:12px">削除</button></div></article>`).join(''); app.innerHTML = `<section class="hero"><div class="eyebrow">MY TEACHING DESK</div><h1>マイ授業デスク</h1><p>保存したテストをクリックすると、元の作成画面に戻れます。</p></section><div class="desk-category"><div class="section-title"><h2>小テスト</h2><p>${tests.length}件</p></div>${tests.length?`<div class="desk-grid">${cards(tests,'小テスト',0,'test')}</div>`:'<div class="empty">小テストの保存データはありません。</div>'}</div><div class="desk-category"><div class="section-title"><h2>復習テスト</h2><p>${reviews.length}件</p></div>${reviews.length?`<div class="desk-grid">${cards(reviews,'復習テスト',0,'review')}</div>`:'<div class="empty">復習テストの保存データはありません。</div>'}</div>`; }
  function deleteSaved(store,index){ const key=store==='review'?'schoolpilot-review-tests':STORAGE_KEY; const items=store==='review'?loadReviewSaved():loadSaved(); if(!items[index])return; if(!window.confirm('この保存データを削除しますか？'))return; items.splice(index,1); localStorage.setItem(key,JSON.stringify(items)); render(); }
  function renderSupportDesk(){ if(state.page!=='desk'||!el('.container')||el('#support-desk-category'))return; const items=loadSupportSaved(); const box=document.createElement('div');box.id='support-desk-category';box.className='desk-category';box.innerHTML=`<div class="section-title"><h2>指導案・板書例</h2><p>${items.length}件</p></div>${items.length?`<div class="desk-grid">${items.map((x,i)=>`<article class="desk-card"><h3>${x.title}</h3><p>${x.level} / ${x.type==='board'?'板書例':'指導案・授業展開例'}</p><div class="actions"><button class="secondary" data-open-support="${i}" style="margin-top:12px">元のデータを開く</button><button class="danger" data-delete-support="${i}" style="margin-top:12px">削除</button></div></article>`).join('')}</div>`:'<div class="empty">保存した指導案・板書例はありません。</div>'}`;el('.container').appendChild(box); }
  function renameSaved(store,index){ const key=store==='review'?'schoolpilot-review-tests':STORAGE_KEY; const items=store==='review'?loadReviewSaved():loadSaved(); if(!items[index])return; const current=items[index].title||`${items[index].grade} ${items[index].subject}「${items[index].unit}」`; const title=window.prompt('保存名を入力してください。',current); if(title===null||!title.trim())return; items[index].title=title.trim(); localStorage.setItem(key,JSON.stringify(items)); render(); }
  function renderDetail(){ app.innerHTML = `<div class="crumbs">ホーム / ${state.grade} / ${state.subject}</div><section class="panel"><div class="unit-head"><div><span class="pill">${state.grade}・${state.subject}</span><h1>「${state.unit}」</h1></div><button class="secondary" data-page="home">単元一覧に戻る</button></div><div class="tabs"><button class="tab active">単元概要</button><button class="tab">45分授業案</button><button class="tab">AI板書</button><button class="tab active">AIミニテスト</button></div><p class="notice">授業レベルを選び、必要な素材のボタンを押してください。MVPではブラウザ内テンプレートから生成します。</p><div class="levels">${levels.map(l=>`<button class="level ${l===state.level?'selected':''}" data-level="${l}">${l}</button>`).join('')}</div><div class="feature"><h2>AI授業案生成 MVP</h2><p>学習目標・授業の流れ・発問・つまずき対応をまとめます。</p><div class="actions"><button class="secondary" data-demo="lesson">45分授業案を生成</button><button class="secondary" data-demo="board">板書案を生成</button></div></div><div class="feature test"><h2>AIミニテスト生成 MVP</h2><p>約5問の選択式・短答・説明問題を、正答とやさしい解説つきで作成します。</p><div class="actions"><button class="primary" id="generate-test">ミニテストを生成</button></div><div id="test-result"></div></div><div class="feature"><h2>AIワークシート生成 MVP</h2><p>児童向けの問題プリントを5問作成します。名前欄つきで、そのまま印刷できます。</p><div class="actions"><button class="primary" id="generate-worksheet">ワークシートを生成</button></div><div id="worksheet-result"></div></div></section>`; }
  function renderDetail(){ app.innerHTML=`<div class="crumbs">ホーム / ${state.grade} / ${state.subject}</div><section class="panel"><div class="unit-head"><div><span class="pill">${state.grade}・${state.subject}</span><h1>「${state.unit}」</h1></div><button class="secondary" data-page="home">ホームに戻る</button></div><div class="tabs"><button class="tab" data-tab="overview">単元概要</button><button class="tab" data-tab="lesson">授業指導案</button><button class="tab" data-tab="board">板書</button><button class="tab" data-tab="test">テスト</button></div><div id="tab-content"></div></section>`; renderActiveTab(); }
  function clearGeneratedContent(){ document.querySelectorAll('#support-result').forEach(n=>n.remove()); state.result=null; state.worksheetResult=null; }
  function renderPackSection(){ return; }
  function renderOverview(){ const pane=el('#tab-content'); if(!pane)return; const ratio=state.grade==='5年'&&state.subject==='算数'&&state.unit==='割合'; const purpose=ratio?'割合を、もとにする量を1とみたときの比べられる量の大きさとして理解し、割合・比べられる量・もとにする量の関係を数・式・数直線で説明できるようにする。':`${state.unit}の基礎的な知識と技能を身に付け、学んだ考え方を使って問題を解決し、理由を説明できるようにする。`; const knowledge=ratio?'割合の意味、百分率、小数との関係を理解している。':`${state.unit}の用語・きまり・基本的な方法を理解している。`; const thinking=ratio?'何をもとにする量とするかを判断し、数直線や式を使って考え方を説明している。':'図・式・言葉を使って考え方を表し、結果を振り返っている。'; const attitude='見通しをもって取り組み、友達の考えと比べながら自分の考えを修正・説明しようとしている。'; const result=ratio?'割合を小数や百分率で表し、割合・比べられる量・もとにする量を求める問題を解決できる。':'学習した内容を使って基本問題と活用問題を解き、学んだことを自分の言葉で振り返ることができる。'; pane.innerHTML=`<div class="overview-card"><span class="pill">指導要領・学習評価を参照</span><h2>単元の目的</h2><p>${purpose}</p><h2>評価の観点</h2><div class="evaluation-grid"><div><b>知識・技能</b><p>${knowledge}</p></div><div><b>思考・判断・表現</b><p>${thinking}</p></div><div><b>主体的に学習に取り組む態度</b><p>${attitude}</p></div></div><h2>学習後に期待する結果</h2><p>${result}</p><p class="source-note">参照：<a href="https://www.mext.go.jp/content/20211102-mxt_kyoiku02-100002607_04.pdf" target="_blank" rel="noopener">文部科学省 小学校学習指導要領解説 算数編</a> ／ <a href="https://www.mext.go.jp/b_menu/hakusho/nc/1415169.htm" target="_blank" rel="noopener">文部科学省 学習評価の通知</a></p></div>`; }
  function renderActiveTab(){ const pane=el('#tab-content'); if(!pane)return; clearGeneratedContent(); document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===state.activeTab)); const levelHtml=`<p class="notice">授業レベルを選び、選択した内容を作成してください。ブラウザ内テンプレートで生成します。</p><div class="levels">${levels.map(l=>`<button class="level ${l===state.level?'selected':''}" data-level="${l}">${l}</button>`).join('')}</div>`; if(state.activeTab==='overview'){pane.innerHTML=`<div class="feature"><h2>単元概要</h2><p>${state.grade} ${state.subject}「${state.unit}」の学習内容を確認し、授業案・板書・テストを準備できます。</p><div class="overview-points"><span>学習内容を整理</span><span>授業時間に合わせて設計</span><span>印刷・保存に対応</span></div></div>`;renderOverview();} else if(state.activeTab==='lesson'){pane.innerHTML=`${levelHtml}<div class="feature"><h2>授業案</h2><p>15分・30分・45分から授業時間を選び、${state.unit}の学習内容を段階的に扱います。</p><div class="minutes">${[15,30,45].map(m=>`<button class="level ${m===state.lessonMinutes?'selected':''}" data-minutes="${m}">${m}分</button>`).join('')}</div><div class="actions"><button class="primary" data-demo="lesson">授業案を作成</button></div></div>`;} else if(state.activeTab==='board'){pane.innerHTML=`${levelHtml}<div class="feature"><h2>板書</h2><p>めあて・問題・考え方・まとめを、黒板の流れに沿って整理します。</p><div class="actions"><button class="primary" data-demo="board">板書例を作成</button></div></div>`;} else {pane.innerHTML=`${levelHtml}<div class="feature test"><h2>小テスト</h2><p>約5問の問題と正答・やさしい解説を作成します。</p><div class="actions"><button class="primary" id="generate-test">小テストを生成</button></div><div id="test-result"></div></div><div class="feature"><h2>復習テスト</h2><p>小テストとは別の問題で、理解の定着を確認します。</p><div class="actions"><button class="primary" id="generate-worksheet">復習テストを生成</button></div><div id="worksheet-result"></div></div>`;} applyLabels(); renderPackSection(); }
  function renderReferences(container,title='参考情報',kind='overview'){ const key=`${state.grade}|${state.subject}|${state.unit}`; const links=(unitReferences[key]&&unitReferences[key][kind])||generalReferenceByKind[kind]||referenceInfo[state.subject]||referenceInfo['算数']; container.insertAdjacentHTML('beforeend',`<div class="reference-card"><h2>${title}</h2><p>この単元・用途に合わせた公開資料です。リンク先の利用条件と学校の採択教科書をご確認ください。</p><div class="reference-grid">${links.map(x=>`<a href="${x[1]}" target="_blank" rel="noopener">${x[0]}<span>公開ページを開く ↗</span></a>`).join('')}</div></div>`); }
  function renderActiveTab(){ const pane=el('#tab-content'); if(!pane)return; clearGeneratedContent(); document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===state.activeTab)); const levelHtml=`<p class="notice">授業レベルを選び、選択した内容を作成してください。ブラウザ内テンプレートで生成します。</p><div class="levels">${levels.map(l=>`<button class="level ${l===state.level?'selected':''}" data-level="${l}">${l}</button>`).join('')}</div>`; if(state.activeTab==='overview'){pane.innerHTML=`<div class="feature"><h2>単元概要</h2><p>${state.grade} ${state.subject}「${state.unit}」の学習内容を確認し、授業案・板書・テストを準備できます。</p><div class="overview-points"><span>学習内容を整理</span><span>授業時間に合わせて設計</span><span>印刷・保存に対応</span></div></div>`;renderOverview();renderReferences(pane,'単元研究・参考情報','overview');} else if(state.activeTab==='lesson'){pane.innerHTML=`${levelHtml}<div class="feature"><h2>授業案（授業指導案）</h2><p>単元の目標、本時の展開、教師の支援、評価と振り返りをつなげて作成します。</p><div class="minutes">${[15,30,45].map(m=>`<button class="level ${m===state.lessonMinutes?'selected':''}" data-minutes="${m}">${m}分</button>`).join('')}</div><div class="actions"><button class="primary" data-demo="lesson">授業案を作成</button></div></div>`;renderReferences(pane,'授業案・指導案の参考情報','lesson');} else if(state.activeTab==='board'){pane.innerHTML=`${levelHtml}<div class="feature"><h2>板書</h2><p>${state.subject}「${state.unit}」の学習過程に合わせた板書例を作成します。</p><div class="actions"><button class="primary" data-demo="board">板書例を作成</button></div></div>`;renderReferences(pane,'板書づくりの参考情報','board');} else {pane.innerHTML=`${levelHtml}<div class="feature test"><h2>小テスト</h2><p>約5問の問題と正答・やさしい解説を作成します。</p><div class="actions"><button class="primary" id="generate-test">小テストを生成</button></div><div id="test-result"></div></div><div class="feature"><h2>復習テスト</h2><p>小テストとは別の問題で、理解の定着を確認します。</p><div class="actions"><button class="primary" id="generate-worksheet">復習テストを生成</button></div><div id="worksheet-result"></div></div>`;pane.insertAdjacentHTML('beforeend',researchBasis);renderReferences(pane,'テスト・教材研究の参考情報','test');} applyLabels(); renderPackSection(); }
  function loadSaved(){ try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');}catch(e){return [];} }
  function saveToDesk(){
    if(!state.result||!state.result.items){ showMessage('先にミニテストを生成してください。'); return false; }
    try{
      const all=loadSaved().filter(x=>!(x.grade===state.grade&&x.subject===state.subject&&x.publisher===state.publisher&&x.unit===state.unit&&x.level===state.level));
      all.unshift({grade:state.grade,subject:state.subject,publisher:state.publisher,unit:state.unit,level:state.level,items:state.result.items,savedAt:new Date().toISOString()});
      localStorage.setItem(STORAGE_KEY,JSON.stringify(all.slice(0,20)));
      return true;
    }catch(e){ showMessage('保存できませんでした。ブラウザのプライベート設定をご確認ください。'); return false; }
  }
  function saveLocalFile(){
    if(!state.result||!state.result.items){ showMessage('先にミニテストを生成してください。'); return; }
    const payload={version:'v12',grade:state.grade,subject:state.subject,unit:state.unit,level:state.level,items:state.result.items,savedAt:new Date().toISOString()};
    const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});
    const url=URL.createObjectURL(blob); const link=document.createElement('a');
    link.href=url; link.download=`${state.grade}_${state.subject}_${state.unit}_ミニテスト.json`;
    document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url);
    showMessage('ローカル保存しました。JSONファイルをダウンロードしました。');
  }
  function buildItems(){ const key=`${state.grade}|${state.subject}|${state.unit}`; if(testSets[key]) return testSets[key]; const base=genericTemplates[state.subject]||genericTemplates.算数; return Array.from({length:5},(_,i)=>({...base[i%base.length],question:`${state.unit}：${base[i%base.length].question}`})); }
  function renderTestResult(){ const r=state.result; if(!r)return; const html=`<div class="result"><h3>${state.grade} ${state.subject}「${state.unit}」のミニテスト（${state.level}）</h3>${researchBasis}${r.items.map((q,i)=>`<article class="question"><div class="question-head"><span class="qno">${i+1}</span><span class="format">${q.format}</span></div><p><strong>${q.question}</strong></p>${q.choices?`<p>${q.choices.map((c,j)=>`${String.fromCharCode(65+j)}．${c}`).join('　')}</p>`:''}<p class="answer">正答：${q.answer}</p><p class="explain">やさしい解説：${q.explain}</p></article>`).join('')}<div class="actions"><button class="primary" id="regenerate-test">作り直す</button><button class="secondary" id="copy-test">コピー</button><button class="secondary" id="save-desk">マイ授業デスクに保存</button><button class="secondary" id="save-local-pdf">PDFでローカル保存</button></div><p id="result-message" class="notice" hidden></p></div>`; el('#test-result').innerHTML=html; applyLabels(); }
  function applyLabels(){ document.querySelectorAll('*').forEach(n=>{if(n.childNodes.length===1&&n.firstChild.nodeType===3)n.textContent=n.textContent.replaceAll('AI','');}); document.querySelectorAll('h2').forEach(n=>{n.textContent=n.textContent.replace('ミニテスト生成 MVP','小テスト生成').replace('ワークシート生成 MVP','復習テスト生成');}); document.querySelectorAll('h3').forEach(n=>{n.textContent=n.textContent.replaceAll('ミニテスト','小テスト').replaceAll('ワークシート','復習テスト');}); document.querySelectorAll('button').forEach(n=>{n.textContent=n.textContent.replace('ミニテストを生成','小テストを生成').replace('ワークシートを生成','復習テストを生成');}); }
  function copyText(){
    if(!state.result||!state.result.items){ showMessage('先にミニテストを生成してください。'); return; }
    const text=state.result.items.map((q,i)=>`${i+1}. ${q.question}\n${q.choices?q.choices.join(' / ')+'\n':''}正答：${q.answer}\nやさしい解説：${q.explain}`).join('\n\n');
    const fallback=()=>{ const area=document.createElement('textarea'); area.value=text; area.setAttribute('readonly',''); area.style.position='fixed'; area.style.opacity='0'; document.body.appendChild(area); area.select(); let ok=false; try{ok=document.execCommand('copy');}catch(e){ok=false;} area.remove(); showMessage(ok?'コピーしました。':'コピーできませんでした。問題文を選択してコピーしてください。'); };
    if(navigator.clipboard&&window.isSecureContext){ navigator.clipboard.writeText(text).then(()=>showMessage('コピーしました。')).catch(fallback); } else { fallback(); }
  }
  function printTestPdf(){
    if(!state.result||!state.result.items){ showMessage('先にミニテストを生成してください。'); return; }
    const popup=window.open('', '_blank');
    if(!popup){ showMessage('PDF画面を開けませんでした。ポップアップを許可してください。'); return; }
    const questionCard=q=>`<article class="q ${q.format==='説明問題'?'q-explain':q.format==='短答'?'q-short':'q-choice'}"><div class="qtop"><span class="num">問題${state.result.items.indexOf(q)+1}</span></div><h2>${q.question}</h2>${q.choices?`<div class="choices">${q.choices.map((c,j)=>`<span>${String.fromCharCode(65+j)}　${c}</span>`).join('')}</div>`:''}<div class="work-label">${q.format==='説明問題'?'考え方を書きましょう。':q.format==='短答'?'答えを書きましょう。':'計算・メモ欄'}</div><div class="answer-line"></div></article>`;
    const answerCard=q=>`<article class="a"><div class="qtop"><span class="num">問題${state.result.items.indexOf(q)+1}</span></div><h2>${q.question}</h2><p class="correct"><b>正答</b>　${q.answer}</p><p><b>やさしい解説</b>　${q.explain}</p></article>`;
    const questions=`<div class="columns"><div class="column">${state.result.items.slice(0,3).map(questionCard).join('')}</div><div class="column">${state.result.items.slice(3).map(questionCard).join('')}</div></div>`;
    const answers=`<div class="columns"><div class="column">${state.result.items.slice(0,3).map(answerCard).join('')}</div><div class="column">${state.result.items.slice(3).map(answerCard).join('')}</div></div>`;
    const css='*{box-sizing:border-box}body{margin:0;color:#203040;font-family:-apple-system,BlinkMacSystemFont,"Noto Sans JP","Yu Gothic",sans-serif;line-height:1.7}.sheet{width:257mm;min-height:364mm;margin:0 auto;padding:17mm 19mm;page-break-after:always}header{display:flex;justify-content:space-between;align-items:end;border-bottom:4px solid #8ed0c1;padding-bottom:10px}.meta{font-size:23px;font-weight:700;color:#18324b;letter-spacing:.08em}.unit-meta{font-size:15px;font-weight:700;color:#18324b}.title{display:flex;align-items:center;gap:10px;margin:20px 0 10px}.title span{font-size:30px}.title h1{margin:0;font-size:30px;color:#18324b}.score-box{margin-left:auto;border:2px solid #18324b;border-radius:4px;min-width:42mm;height:14mm;padding:2mm 3mm;font-size:20px;text-align:right;color:#18324b}.score-box span{font-size:12px}.columns{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:12mm;align-items:start}.column{min-width:0}.q,.a{border:2px solid #dbe4ed;border-radius:14px;padding:11px 13px;margin:10px 0;background:#fbfdff;break-inside:avoid;min-height:50mm}.q:nth-child(odd),.a:nth-child(odd){border-color:#bfe5dc;background:#f5fffc}.qtop{display:flex;align-items:center;gap:8px}.num{display:inline-flex;align-items:center;justify-content:center;background:#18324b;color:#fff;border-radius:8px;min-width:27mm;height:9mm;padding:0 5px;font-size:14px;font-weight:800}.q h2,.a h2{font-size:16px;margin:7px 0;color:#203040}.choices{display:grid;grid-template-columns:1fr;gap:6px;margin:8px 0}.choices span{border:1px solid #dbe4ed;border-radius:8px;padding:5px 8px;background:#fff}.work-label{font-size:11px;color:#6b7b8d;margin-top:8px}.answer-line{height:38px;border-bottom:1px dashed #aebdca;margin-top:5px}.q-short .answer-line{height:55px}.q-explain .answer-line{height:82px}.a p{font-size:13px;margin:6px 0}.correct{background:#e8f7f1;border-radius:8px;padding:7px 10px;color:#146c4b}.a b{color:#18324b}@page{size:B4 portrait;margin:0}@media print{.sheet{margin:0}}';
    popup.document.write(`<!doctype html><html lang="ja"><head><meta charset="utf-8"><title>${state.unit} 練習問題</title><style>${css}</style></head><body><section class="sheet"><header><div class="meta">名前：　　　　　　　　　　　　　　　　</div><div class="unit-meta">${state.grade} ${state.subject}「${state.unit}」</div></header><div class="title"><span>✏️</span><h1>練習問題</h1><div class="score-box">　　　<span>点</span></div></div>${questions}</section><section class="sheet"><header><div class="unit-meta">${state.grade} ${state.subject}「${state.unit}」</div></header><div class="title"><span>🌟</span><h1>答え・やさしい解説</h1></div>${answers}</section><script>window.onload=function(){window.print();};<\/script></body></html>`); popup.document.close();
  }
  function buildWorksheet(){
    if(state.grade==='5年'&&state.subject==='算数'&&state.unit==='割合') return [
      {question:'200円の15%はいくらですか。式と答えを書きましょう。',answer:'30円',explain:'200×0.15＝30です。'},
      {question:'80人のうち男子が32人でした。男子は全体の何%ですか。',answer:'40%',explain:'32÷80＝0.4なので40%です。'},
      {question:'定価1,200円の25%引きの値段を求めましょう。',answer:'900円',explain:'25%引きは75%の値段なので、1200×0.75＝900円です。'},
      {question:'もとにする量が60、割合が0.4のとき、比べる量を求めましょう。',answer:'24',explain:'60×0.4＝24です。'},
      {question:'ある数の30%が18です。ある数を求めましょう。',answer:'60',explain:'18÷0.3＝60です。'}
    ];
    return [`${state.unit}で大切な言葉を一つ書きましょう。`,`「${state.unit}」で学んだことを使って答えましょう。`,`答えの理由や考え方を書きましょう。`,'学んだことを図や式で表しましょう。','今日の学習で分かったことを書きましょう。'].map(question=>({question,answer:'',explain:'学習内容を振り返りましょう。'}));
  }
  function renderWorksheetResult(){ if(!state.worksheetResult)return; const card=(q,i)=>`<article class="question"><div class="question-head"><span class="qno">${i+1}</span></div><p><strong>${q.question}</strong></p><p class="answer">正答：${q.answer||'記入内容を確認'}</p><p class="explain">やさしい解説：${q.explain}</p></article>`; el('#worksheet-result').innerHTML=`<div class="result"><h3>${state.grade} ${state.subject}「${state.unit}」ワークシート（${state.level}）</h3>${researchBasis}<div class="worksheet-preview"><div class="worksheet-column">${state.worksheetResult.slice(0,3).map((q,i)=>card(q,i)).join('')}</div><div class="worksheet-column">${state.worksheetResult.slice(3).map((q,i)=>card(q,i+3)).join('')}</div></div><div class="actions"><button class="primary" id="regenerate-worksheet">作り直す</button><button class="secondary" id="copy-worksheet">コピー</button><button class="secondary" id="save-worksheet-desk">マイ授業デスクに保存</button><button class="secondary" id="save-worksheet-pdf">PDFでローカル保存</button></div><p id="worksheet-message" class="notice" hidden></p></div>`; applyLabels(); }
  function copyWorksheet(){ const text=state.worksheetResult.map((q,i)=>`問題${i+1}：${q.question}\n正答：${q.answer}\nやさしい解説：${q.explain}`).join('\n\n'); navigator.clipboard?.writeText(text).then(()=>{const n=el('#worksheet-message');n.hidden=false;n.textContent='コピーしました。';}).catch(()=>{const n=el('#worksheet-message');n.hidden=false;n.textContent='コピーできませんでした。問題文を選択してコピーしてください。';}); }
  function saveWorksheetToDesk(){ try{const key='schoolpilot-review-tests';const all=JSON.parse(localStorage.getItem(key)||'[]').filter(x=>!(x.grade===state.grade&&x.subject===state.subject&&x.publisher===state.publisher&&x.unit===state.unit&&x.level===state.level));all.unshift({grade:state.grade,subject:state.subject,publisher:state.publisher,unit:state.unit,level:state.level,items:state.worksheetResult,savedAt:new Date().toISOString()});localStorage.setItem(key,JSON.stringify(all.slice(0,20)));const n=el('#worksheet-message');if(n){n.hidden=false;n.textContent='同じ内容がある場合は上書きして、マイ授業デスクに保存しました。';}}catch(e){const n=el('#worksheet-message');if(n){n.hidden=false;n.textContent='保存できませんでした。';}} }
  function renderSupportResult(type){ const isBoard=type==='board'; const title=isBoard?'板書例':'指導案・授業展開例'; const content=isBoard?['めあて：割合の求め方を考えよう','問題：120円の20%はいくら？','数直線で「もとにする量」と「比べられる量」を確認','割合＝比べられる量÷もとにする量','まとめ：割合は、もとにする量を1とみたときの比']:[]; const lesson=['導入 5分：身近な割合の場面を提示','問題提示 5分：何を1とみるか考える','個人思考 10分：数直線と式で表す','交流 15分：考え方を比べる','まとめ 5分：公式と言葉を整理','振り返り 5分：分かったことを書く']; const rows=isBoard?content:lesson; const box=el('.panel'); if(!box)return; let old=el('#support-result'); if(!old){old=document.createElement('div');old.id='support-result';old.className='support-result';box.appendChild(old);} old.innerHTML=`<div class="result"><h3>${state.grade} ${state.subject}「${state.unit}」${title}</h3><div class="support-paper">${rows.map((x,i)=>`<div class="support-row"><b>${i+1}</b><span>${x}</span></div>`).join('')}</div><div class="actions"><button class="primary" id="print-support" data-support-type="${type}">印刷</button><button class="secondary" id="save-support" data-support-type="${type}">マイ授業デスクに保存</button></div></div>`; }
  const subjectBoardPlan={
    '国語':['めあて：本文の表現と根拠に着目して考えよう','教材文：大事な言葉・心が動いた表現','問い：なぜそう考えたのか','本文の言葉を根拠にして考えを比較','まとめ：分かったこと・次に読みたいこと'],
    '算数':['めあて：図・式・言葉で考え方を説明しよう','問題：何を求める問題かを確かめる','見通し：使う数量・図・式を予想する','考え方を並べて、共通点と違いを比べる','まとめ：きまり・公式・確かめ方'],
    '理科':['問題：どのような変化やきまりがあるだろう','予想：理由を付けて予想する','実験方法：変える条件・そろえる条件を確認','結果：表や図で事実を記録する','考察・まとめ：結果から言えることを書く'],
    '社会':['めあて：資料から事実と特色を読み取ろう','問い：何が分かれば説明できるか','資料：地図・グラフ・写真から事実を拾う','気づき：地域・時期・立場で比べる','まとめ：資料を根拠に社会の仕組みを説明する'],
    '英語':['めあて：相手に伝わる表現を使おう','今日の表現：聞く・話すための語句を確認','モデル：教師と児童のやり取りを見る','活動：ペアで伝え合い、聞き返す','振り返り：使えた表現と次の目標']
  };
  const subjectLessonPlan={
    '国語':['導入：教材と本時のめあてを確認','読む・考える：本文の言葉に線を引き、自分の考えを書く','交流：根拠を示しながら考えを伝え合う','整理：共通点・相違点を板書で整理','評価・振り返り：根拠を用いて説明できたか確認'],
    '算数':['導入：既習事項と本時の問題をつなぐ','自力解決：図・式・言葉で見通しをもって考える','交流：複数の考えを比較し、よさを説明する','まとめ：きまりや公式を言葉で整理する','評価・振り返り：類題で使えるか確かめる'],
    '理科':['問題づくり：自然事象を観察して問いを立てる','予想：根拠をもって予想し、条件を整理する','観察・実験：安全に実施し、事実を記録する','考察：予想と結果を比べてきまりを考える','評価・振り返り：結果から説明できたか確認'],
    '社会':['導入：写真・地図・グラフから疑問をもつ','資料活用：複数資料から事実を読み取る','比較・検討：地域や時期、立場の違いで考える','説明：資料を根拠に自分の考えを伝える','評価・振り返り：社会の仕組みと自分の生活をつなぐ'],
    '英語':['導入：場面と本時の表現を聞く','練習：意味と音を確認し、短いやり取りをする','活動：目的をもってペアで伝え合う','共有：伝わった表現や工夫を振り返る','評価・振り返り：聞く・話す活動の様子を見取る']
  };
  const referenceInfo={
    '国語':[['文部科学省 学習指導要領解説 国語','https://www.mext.go.jp/a_menu/shotou/new-cs/youryou/syokaisetsu/'],['東京書籍 ウェブ指導案「新編 新しい国語」','https://sites.google.com/tokyo-shoseki.co.jp/kokugo-shidoan/'],['小学校国語科 授業アシスト 板書アイディア53','https://www.meijitosho.co.jp/detail/4-18-037423-6']],
    '算数':[['文部科学省 学習指導要領解説 算数','https://www.mext.go.jp/a_menu/shotou/new-cs/youryou/syokaisetsu/'],['啓林館 指導書活用Navi（板書指導案・教材）','https://www.shinko-keirin.co.jp/keirinkan/sho/sansu/navi/'],['京都教育大学 教科別学習指導案例（算数）','https://www.kyokyo-u.ac.jp/kyoumu/jicci/sidouan/']],
    '理科':[['文部科学省 学習指導要領解説 理科','https://www.mext.go.jp/a_menu/shotou/new-cs/youryou/syokaisetsu/'],['京都教育大学 教科別学習指導案例（理科）','https://www.kyokyo-u.ac.jp/kyoumu/jicci/sidouan/'],['NITS 教材研究の方法（発問・板書計画）','https://www.nits.go.jp/materials/basic/files/012_001.pdf']],
    '社会':[['文部科学省 学習指導要領解説 社会','https://www.mext.go.jp/a_menu/shotou/new-cs/youryou/syokaisetsu/'],['京都教育大学 教科別学習指導案例（社会）','https://www.kyokyo-u.ac.jp/kyoumu/jicci/sidouan/'],['学びの場.com 指導案データベース','https://www.manabinoba.com/plans/']],
    '英語':[['文部科学省 学習指導要領解説 外国語活動・外国語','https://www.mext.go.jp/a_menu/shotou/new-cs/youryou/syokaisetsu/'],['京都教育大学 教科別学習指導案例（外国語）','https://www.kyokyo-u.ac.jp/kyoumu/jicci/sidouan/'],['学びの場.com 指導案データベース','https://www.manabinoba.com/plans/']]
  };
  const unitReferences={
    '5年|算数|割合':{
      overview:[['文部科学省 学習指導要領解説 算数編','https://www.mext.go.jp/a_menu/shotou/new-cs/youryou/syokaisetsu/'],['岡山県総合教育センター「割合」の指導法','https://www.pref.okayama.jp/page/846180.html'],['啓林館 小学校算数5年 編修趣意書','https://www.shinko-keirin.co.jp/keirinkan/sho/text_2020/sansu/file/sansu_prospectus05.pdf']],
      lesson:[['EDUPEDIA 割合の存在に気づかせる授業案','https://edupedia.jp/archives/46984'],['大阪教育大学附属平野小学校 算数「割合」指導案','https://www.osaka-kyoiku.ac.jp/~hirasho/h27research/togasaki.pdf'],['ロイロノート 小5算数「割合」授業案','https://help.loilonote.app/--66a7479eabe4d5001d0113e5'],['岡山県総合教育センター 割合の指導例・単元計画','https://www.pref.okayama.jp/page/846180.html'],['啓林館 指導書活用Navi 指導案の書き方','https://www.shinko-keirin.co.jp/keirinkan/sho/sansu/navi/'],['NITS 教材研究の方法・発問計画・板書計画','https://www.nits.go.jp/materials/basic/files/012_001.pdf']],
      board:[['岡山県総合教育センター 割合の板書例','https://www.pref.okayama.jp/page/846180.html'],['文部科学省 小学校5年算数 指導資料集（割合の板書計画）','https://www.mext.go.jp/a_menu/shotou/clarinet/002/20210817-mxt_kouhou02_5.pdf'],['東洋館出版社 小学校5年算数 板書シリーズ','https://www.toyokan.co.jp/products/3993'],['東書Eネット 板書の技法・算数資料','https://ten.tokyo-shoseki.co.jp/shinninh/bansho/documents/'],['明治図書「板書力は授業力」','https://www.meijitosho.co.jp/sp/eduzine/opinion/?id=20130390'],['みんなの教育技術「単元別 板書の技術」','https://kyoiku.sho.jp/special/137931/']],
      test:[['すらぷり 小5算数 割合','https://surapuri.jp/elementary_school05/wariai/'],['ちびむすドリル 割合プリント','https://happylilac.net/keisan-wariai.html'],['ぷりんと365 小5算数 比べ方・割合','https://www.print365.net/kurabekatabunsyo5nen/'],['大阪府 力だめしプリント 小5算数 割合','https://www.pref.osaka.lg.jp/o180080/shochugakko/chikaradamesi5/index.html']]
    }
  };
  const generalReferenceByKind={
    overview:[['文部科学省 小学校学習指導要領解説','https://www.mext.go.jp/a_menu/shotou/new-cs/youryou/syokaisetsu/'],['文部科学省 学習評価の通知','https://www.mext.go.jp/b_menu/hakusho/nc/1415169.htm'],['教育出版 年間指導計画・評価計画','https://www.kyoiku-shuppan.co.jp/tokushu/r6plan.html']],
    lesson:[['京都教育大学 教科別学習指導案例','https://www.kyokyo-u.ac.jp/kyoumu/jicci/sidouan/'],['学びの場.com 指導案データベース','https://www.manabinoba.com/plans/'],['熊本大学附属小学校 教科別指導案','https://www.educ.kumamoto-u.ac.jp/elem/the_study/instructional_plan/'],['東京都教職員研修センター 学習指導案のページ','https://www.kyoiku-kensyu.metro.tokyo.lg.jp/08ojt/helpdesk/plans/'],['東京書籍 ウェブ指導案「新編 新しい国語」','https://sites.google.com/tokyo-shoseki.co.jp/kokugo-shidoan/'],['NITS 授業・単元づくり 教材研究の方法','https://www.nits.go.jp/materials/basic/files/012_001.pdf'],['文部科学省 小学校学習指導要領解説','https://www.mext.go.jp/a_menu/shotou/new-cs/youryou/syokaisetsu/']],
    board:[['東書Eネット 板書関連資料集','https://ten.tokyo-shoseki.co.jp/shinninh/bansho/documents/'],['教育出版「プロの板書」','https://www.kyoiku-shuppan.co.jp/book/book/cate5/cate505/sho-1917.html'],['東洋館出版社 板書シリーズ','https://www.toyokan.co.jp/products/3993'],['明治図書「板書力は授業力」','https://www.meijitosho.co.jp/sp/eduzine/opinion/?id=20130390'],['みんなの教育技術「単元別 板書の技術」','https://kyoiku.sho.jp/special/137931/']],
    test:[['すらぷり 公開教材','https://surapuri.jp/'],['ちびむすドリル 公開教材','https://happylilac.net/'],['ぷりんと365 公開教材','https://www.print365.net/']]
  };
  function renderSupportResult(type){ const isBoard=type==='board'; const title=isBoard?'板書例':'授業指導案'; const rows=isBoard?(subjectBoardPlan[state.subject]||subjectBoardPlan['算数']):(subjectLessonPlan[state.subject]||subjectLessonPlan['算数']); const box=el('.panel'); if(!box)return; let old=el('#support-result'); if(!old){old=document.createElement('div');old.id='support-result';old.className='support-result';box.appendChild(old);} old.innerHTML=`<div class="result"><h3>${state.grade} ${state.subject}「${state.unit}」${title}</h3><p class="source-note">${isBoard?'教科の学び方に合わせて、ねらい・中心資料・考えの交流・まとめが見える板書構成です。':'単元の目標・学習活動・教師の支援・評価がつながる授業指導案の構成です。'}</p><div class="support-paper">${rows.map((x,i)=>`<div class="support-row"><b>${i+1}</b><span>${x}</span></div>`).join('')}</div><div class="actions"><button class="primary" id="print-support" data-support-type="${type}">印刷</button><button class="secondary" id="save-support" data-support-type="${type}">マイ授業デスクに保存</button></div></div>`; if(isBoard&&state.subject==='算数')addBoardVisual(); }
  function renderReferences(container,title='参考情報'){ const links=referenceInfo[state.subject]||referenceInfo['算数']; container.insertAdjacentHTML('beforeend',`<div class="reference-card"><h2>${title}</h2><p>公開されている学習指導要領・指導案・板書資料・書籍情報を、教材研究の入口として確認できます。リンク先の利用条件と学校の採択教科書をご確認ください。</p><div class="reference-grid">${links.map(x=>`<a href="${x[1]}" target="_blank" rel="noopener">${x[0]}<span>公開ページを開く ↗</span></a>`).join('')}</div></div>`); }
  function renderActiveTab(){ const pane=el('#tab-content'); if(!pane)return; clearGeneratedContent(); document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===state.activeTab)); const levelHtml=`<p class="notice">授業レベルを選び、選択した内容を作成してください。ブラウザ内テンプレートで生成します。</p><div class="levels">${levels.map(l=>`<button class="level ${l===state.level?'selected':''}" data-level="${l}">${l}</button>`).join('')}</div>`; if(state.activeTab==='overview'){pane.innerHTML=`<div class="feature"><h2>単元概要</h2><p>${state.grade} ${state.subject}「${state.unit}」の学習内容を確認し、授業案・板書・テストを準備できます。</p><div class="overview-points"><span>学習内容を整理</span><span>授業時間に合わせて設計</span><span>印刷・保存に対応</span></div></div>`;renderOverview();renderReferences(pane,'単元研究・参考情報');} else if(state.activeTab==='lesson'){pane.innerHTML=`${levelHtml}<div class="feature"><h2>授業案（授業指導案）</h2><p>単元の目標、本時の展開、教師の支援、評価と振り返りをつなげて作成します。</p><div class="minutes">${[15,30,45].map(m=>`<button class="level ${m===state.lessonMinutes?'selected':''}" data-minutes="${m}">${m}分</button>`).join('')}</div><div class="actions"><button class="primary" data-demo="lesson">授業案を作成</button></div></div>`;renderReferences(pane,'授業案・指導案の参考情報');} else if(state.activeTab==='board'){pane.innerHTML=`${levelHtml}<div class="feature"><h2>板書</h2><p>${state.subject}の学習過程に合わせて、めあて・中心資料・考えの交流・まとめが見える構成で作成します。</p><div class="actions"><button class="primary" data-demo="board">板書例を作成</button></div></div>`;renderReferences(pane,'板書づくりの参考情報');} else {pane.innerHTML=`${levelHtml}<div class="feature test"><h2>小テスト</h2><p>約5問の問題と正答・やさしい解説を作成します。</p><div class="actions"><button class="primary" id="generate-test">小テストを生成</button></div><div id="test-result"></div></div><div class="feature"><h2>復習テスト</h2><p>小テストとは別の問題で、理解の定着を確認します。</p><div class="actions"><button class="primary" id="generate-worksheet">復習テストを生成</button></div><div id="worksheet-result"></div></div>`;pane.insertAdjacentHTML('beforeend',researchBasis);renderReferences(pane,'テスト・教材研究の参考情報');} applyLabels(); renderPackSection(); }
  function addBoardVisual(){ const paper=el('#support-result .support-paper'); if(!paper||el('#board-visual'))return; const rows=Array.from(paper.querySelectorAll('.support-row span')).map(x=>x.textContent||''); if(!rows.length)return; const textOf=x=>{const p=String(x||'').split('：');return {label:p.shift()||'板書',text:p.join('：')||String(x||'')};}; const parts=[textOf(rows[0]),textOf(rows[Math.min(1,rows.length-1)]),textOf(rows[rows.length-1])]; const icons={国語:'📖',算数:'🔢',理科:'🔬',社会:'🗺️',英語:'🔤'}; const middle=state.subject==='理科'?'🧪':state.subject==='社会'?'🗺️':state.subject==='英語'?'💬':icons[state.subject]||'📝'; paper.insertAdjacentHTML('beforebegin',`<div id="board-visual" class="board-visual"><div class="board-head">黒板イメージ</div><div class="board-columns"><div class="board-part"><span class="board-icon">${icons[state.subject]||'🎯'}</span><b>${parts[0].label}</b><p>${parts[0].text}</p></div><div class="board-part"><span class="board-icon">${middle}</span><b>${parts[1].label}</b><p>${parts[1].text}</p><div class="board-note">${rows.length>2?textOf(rows[2]).text:''}</div></div><div class="board-part"><span class="board-icon">✅</span><b>${parts[2].label}</b><p>${parts[2].text}</p></div></div></div>`); }
  function saveSupport(type){ const node=el('#support-result'); if(!node)return; const rows=Array.from(node.querySelectorAll('.support-row')).map(r=>r.querySelector('span').textContent); try{const key='schoolpilot-support-materials';const current=JSON.parse(localStorage.getItem(key)||'[]');const all=current.filter(x=>!(x.grade===state.grade&&x.subject===state.subject&&x.unit===state.unit&&x.level===state.level&&x.type===type));all.unshift({grade:state.grade,subject:state.subject,unit:state.unit,level:state.level,type,title:node.querySelector('h3').textContent,rows,savedAt:new Date().toISOString()});localStorage.setItem(key,JSON.stringify(all.slice(0,20)));node.querySelector('.result').insertAdjacentHTML('beforeend',`<p class="notice">同じ内容がある場合は上書きして、マイ授業デスクに保存しました。</p><div class="actions"><button class="secondary" data-return-support="${type}">${type==='board'?'板書':'指導案'}に戻る</button></div>`);}catch(e){} }
  function printSupport(){ const node=el('#support-result'); if(!node)return; const popup=window.open('','_blank'); if(!popup)return; popup.document.write(`<html lang="ja"><head><meta charset="utf-8"><title>${state.unit} 授業準備</title><style>@page{size:A4 portrait;margin:0}body{font-family:"Yu Gothic",sans-serif;padding:18mm;color:#203040}h1{font-size:25px;border-bottom:3px solid #8ed0c1;padding-bottom:10px}.meta{font-size:14px;color:#526576;margin-bottom:16px}.row{border:1px solid #bfe5dc;border-radius:10px;padding:13px;margin:10px 0;display:flex;gap:12px;min-height:22mm}.row b{background:#18324b;color:#fff;border-radius:50%;width:28px;height:28px;text-align:center;padding-top:2px}.row span{font-size:16px;font-weight:700}</style></head><body><h1>${state.subject}「${state.unit}」${node.querySelector('h3').textContent.split('」')[1]||''}</h1><div class="meta">${state.grade} / 授業レベル：${state.level}</div>${Array.from(node.querySelectorAll('.support-row')).map(r=>`<div class="row"><b>${r.querySelector('b').textContent}</b><span>${r.querySelector('span').textContent}</span></div>`).join('')}<script>window.onload=function(){window.print();};<\/script></body></html>`); popup.document.close(); }
  function printWorksheet(){ const popup=window.open('','_blank'); if(!popup)return; const card=(q,i)=>`<article><b>問題${i+1}</b><p>${q}</p><div></div></article>`; const left=state.worksheetResult.slice(0,3).map((q,i)=>card(q,i)).join(''); const right=state.worksheetResult.slice(3).map((q,i)=>card(q,i+3)).join(''); const answerItems=buildItems(); const answerCard=(q,i)=>`<article class="answer"><b>問題${i+1}</b><p><strong>正答：</strong>${q.answer}</p><p class="explain">${q.explain}</p></article>`; const answerLeft=answerItems.slice(0,3).map((q,i)=>answerCard(q,i)).join(''); const answerRight=answerItems.slice(3).map((q,i)=>answerCard(q,i+3)).join(''); popup.document.write(`<html lang="ja"><head><meta charset="utf-8"><title>復習テスト</title><style>@page{size:B4 portrait;margin:0}body{font-family:"Yu Gothic",sans-serif;padding:18mm;color:#203040}h1{font-size:28px;border-bottom:3px solid #8ed0c1;padding-bottom:10px}header{font-size:22px;margin-bottom:15px}main{display:grid;grid-template-columns:1fr 1fr;gap:12mm;align-items:start}.column{min-width:0}article{border:2px solid #bfe5dc;border-radius:14px;padding:14px;margin:0 0 12px;min-height:48mm;break-inside:avoid}article:nth-child(even){border-color:#f5d7a9}article b{display:inline-block;background:#18324b;color:#fff;border-radius:7px;padding:3px 9px}article p{font-size:18px;font-weight:700}article div{height:40px;border-bottom:1px dashed #aebdca;margin-top:16px}.answers{page-break-before:always}.answer{min-height:35mm}.answer p{font-size:15px;font-weight:400}.answer .explain{font-size:13px;color:#526576}</style></head><body><header>名前：　　　　　　　　　　　　　　${state.grade} ${state.subject}「${state.unit}」</header><h1>復習テスト</h1><main><div class="column">${left}</div><div class="column">${right}</div></main><section class="answers"><h1>復習テスト　回答・解説</h1><main><div class="column">${answerLeft}</div><div class="column">${answerRight}</div></main></section><script>window.onload=function(){window.print();};<\/script></body></html>`); popup.document.close(); }
  function printWorksheet(){ const popup=window.open('','_blank'); if(!popup)return; const card=(q,i)=>`<article><b>問題${i+1}</b><p>${q.question}</p><div></div></article>`; const left=state.worksheetResult.slice(0,3).map((q,i)=>card(q,i)).join(''); const right=state.worksheetResult.slice(3).map((q,i)=>card(q,i+3)).join(''); const answerCard=(q,i)=>`<article class="answer"><b>問題${i+1}</b><p><strong>正答：</strong>${q.answer||'記入内容を確認'}</p><p class="explain">${q.explain}</p></article>`; const answerLeft=state.worksheetResult.slice(0,3).map((q,i)=>answerCard(q,i)).join(''); const answerRight=state.worksheetResult.slice(3).map((q,i)=>answerCard(q,i+3)).join(''); popup.document.write(`<html lang="ja"><head><meta charset="utf-8"><title>復習テスト</title><style>@page{size:B4 portrait;margin:0}body{font-family:"Yu Gothic",sans-serif;padding:18mm;color:#203040}h1{font-size:28px;border-bottom:3px solid #8ed0c1;padding-bottom:10px}header{font-size:22px;margin-bottom:15px;display:flex;justify-content:space-between}.score{border:2px solid #18324b;padding:5px 20px;font-size:15px}main{display:grid;grid-template-columns:1fr 1fr;gap:12mm;align-items:start}.column{min-width:0}article{border:2px solid #bfe5dc;border-radius:14px;padding:14px;margin:0 0 12px;min-height:48mm;break-inside:avoid}article:nth-child(even){border-color:#f5d7a9}article b{display:inline-block;background:#18324b;color:#fff;border-radius:7px;padding:3px 9px}article p{font-size:18px;font-weight:700}article div{height:40px;border-bottom:1px dashed #aebdca;margin-top:16px}.answers{page-break-before:always}.answer{min-height:35mm}.answer p{font-size:15px;font-weight:400}.answer .explain{font-size:13px;color:#526576}</style></head><body><header><span>名前：　　　　　　　　　　　　　　${state.grade} ${state.subject}「${state.unit}」</span><span class="score">　　　点</span></header><h1>復習テスト</h1><main><div class="column">${left}</div><div class="column">${right}</div></main><section class="answers"><h1>復習テスト　回答・解説</h1><main><div class="column">${answerLeft}</div><div class="column">${answerRight}</div></main></section><script>window.onload=function(){window.print();};<\/script></body></html>`); popup.document.close(); }
  function showMessage(msg){ const node=el('#result-message'); if(node){node.hidden=false;node.textContent=msg;} }
  function boardReferenceBlock(){ const key=`${state.grade}|${state.subject}|${state.unit}`; const links=(unitReferences[key]&&unitReferences[key].board)||generalReferenceByKind.board; return `<div class="reference-card board-reference-inline"><h2>板書作りの参考情報</h2><p>板書の見通し、構造化、文字量、発問とのつながりを確認できる公開資料です。</p><div class="reference-grid">${links.map(x=>`<a href="${x[1]}" target="_blank" rel="noopener">${x[0]}<span>参考リンクを開く ↗</span></a>`).join('')}</div></div>`; }
  function renderSupportResult(type){ const isBoard=type==='board'; const title=isBoard?'板書例':'授業指導案'; const rows=isBoard?(subjectBoardPlan[state.subject]||subjectBoardPlan['算数']):(subjectLessonPlan[state.subject]||subjectLessonPlan['算数']); const box=el('.panel'); if(!box)return; let old=el('#support-result'); if(!old){old=document.createElement('div');old.id='support-result';old.className='support-result';box.appendChild(old);} old.innerHTML=`<div class="result"><h3>${state.grade} ${state.subject}「${state.unit}」${title}</h3><p class="source-note">${isBoard?'教科の学び方に合わせて、ねらい・中心資料・考えの交流・まとめが見える板書構成です。':'単元の目標・学習活動・教師の支援・評価がつながる授業指導案の構成です。'}</p><div class="support-paper">${rows.map((x,i)=>`<div class="support-row"><b>${i+1}</b><span>${x}</span></div>`).join('')}</div><div class="actions"><button class="primary" id="print-support" data-support-type="${type}">印刷</button><button class="secondary" id="save-support" data-support-type="${type}">マイ授業デスクに保存</button></div>${isBoard?boardReferenceBlock():''}</div>`; if(isBoard&&state.subject==='算数')addBoardVisual(); }
  function renderSupportResult(type){ const isBoard=type==='board'; const title=isBoard?'板書例':'授業指導案'; const rows=isBoard?(subjectBoardPlan[state.subject]||subjectBoardPlan['算数']):(subjectLessonPlan[state.subject]||subjectLessonPlan['算数']); const box=el('.panel'); if(!box)return; let old=el('#support-result'); if(!old){old=document.createElement('div');old.id='support-result';old.className='support-result';box.appendChild(old);} old.innerHTML=`<div class="result"><h3>${state.grade} ${state.subject}「${state.unit}」${title}</h3><p class="source-note">${isBoard?'教科の学び方に合わせて、ねらい・中心資料・考えの交流・まとめが見える板書構成です。':'単元の目標・学習活動・教師の支援・評価がつながる授業指導案の構成です。'}</p><div class="support-paper">${rows.map((x,i)=>`<div class="support-row"><b>${i+1}</b><span>${x}</span></div>`).join('')}</div><div class="actions"><button class="primary" id="print-support" data-support-type="${type}">印刷</button><button class="secondary" id="save-support" data-support-type="${type}">マイ授業デスクに保存</button></div></div>`; if(isBoard&&state.subject==='算数')addBoardVisual(); }
  function renderReferences(container,title='参考情報',kind='overview'){ const key=`${state.grade}|${state.subject}|${state.unit}`; const links=(unitReferences[key]&&unitReferences[key][kind])||generalReferenceByKind[kind]||referenceInfo[state.subject]||referenceInfo['算数']; container.insertAdjacentHTML('beforeend',`<div class="reference-card"><h2>${title}</h2><p>この単元・用途に合わせた公開資料です。リンク先の利用条件と学校の採択教科書をご確認ください。</p><div class="reference-grid">${links.map(x=>`<a href="${x[1]}" target="_blank" rel="noopener">${x[0]}<span>参考リンクを開く ↗</span></a>`).join('')}</div></div>`); }
  function renderActiveTab(){ const pane=el('#tab-content'); if(!pane)return; clearGeneratedContent(); document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===state.activeTab)); const levelHtml=`<p class="notice">授業レベルを選び、選択した内容を作成してください。ブラウザ内テンプレートで生成します。</p><div class="levels">${levels.map(l=>`<button class="level ${l===state.level?'selected':''}" data-level="${l}">${l}</button>`).join('')}</div>`; if(state.activeTab==='overview'){pane.innerHTML=`<div class="feature"><h2>単元概要</h2><p>${state.grade} ${state.subject}「${state.unit}」の学習内容を確認し、授業案・板書・テストを準備できます。</p><div class="overview-points"><span>学習内容を整理</span><span>授業時間に合わせて設計</span><span>印刷・保存に対応</span></div></div>`;renderOverview();renderReferences(pane,'単元研究・参考情報','overview');} else if(state.activeTab==='lesson'){pane.innerHTML=`${levelHtml}<div class="feature"><h2>授業案（授業指導案）</h2><p>単元の目標、本時の展開、教師の支援、評価と振り返りをつなげて作成します。</p><div class="minutes">${[15,30,45].map(m=>`<button class="level ${m===state.lessonMinutes?'selected':''}" data-minutes="${m}">${m}分</button>`).join('')}</div><div class="actions"><button class="primary" data-demo="lesson">授業案を作成</button></div></div>`;renderReferences(pane,'授業案・指導案の参考情報','lesson');} else if(state.activeTab==='board'){pane.innerHTML=`${levelHtml}<div class="feature"><h2>板書</h2><p>${state.subject}「${state.unit}」の学習過程に合わせた板書例を作成します。</p><div class="actions"><button class="primary" data-demo="board">板書例を作成</button></div></div>`;renderReferences(pane,'板書づくりの参考情報','board');} else {pane.innerHTML=`${levelHtml}<div class="feature test"><h2>小テスト</h2><p>約5問の問題と正答・やさしい解説を作成します。</p><div class="actions"><button class="primary" id="generate-test">小テストを生成</button></div><div id="test-result"></div></div><div class="feature"><h2>復習テスト</h2><p>小テストとは別の問題で、理解の定着を確認します。</p><div class="actions"><button class="primary" id="generate-worksheet">復習テストを生成</button></div><div id="worksheet-result"></div></div>`;pane.insertAdjacentHTML('beforeend',researchBasis);renderReferences(pane,'テスト・教材研究の参考情報','test');} applyLabels(); }
  function normalizeLessonLabels(){ if(state.activeTab!=='lesson')return; const title=document.querySelector('#tab-content h2'); if(title)title.textContent='授業指導案'; const create=document.querySelector('#tab-content [data-demo="lesson"]'); if(create)create.textContent='授業指導案を作成'; const ref=document.querySelector('#tab-content .reference-card h2'); if(ref)ref.textContent='授業指導案の参考情報'; }
  function ensureTabBackButton(){ const pane=el('#tab-content'); if(pane&&!pane.querySelector('[data-tab-back]'))pane.insertAdjacentHTML('beforeend','<div class="tab-back"><button class="secondary" data-back data-tab-back>戻る</button></div>'); }
  const firstGradeMathBoard=['めあて：かずやかたちのひみつをみつけよう','問題：いくつあるかな・どちらがおおいかな','図やブロック：見えたことを絵や数で表す','友だちの考え：同じところ・ちがうところ','まとめ：数・式・図を使うと分かりやすい'];
  const firstGradeMathLesson=['導入：身近なものを数えたり比べたりする','活動：具体物・絵・数図ブロックを操作する','交流：どのように考えたかを指で示して伝える','整理：絵・式・言葉をつないで表す','評価・振り返り：できたことを絵や言葉で確かめる'];
  const secondGradeMathBoard=['めあて：図や式を使って、きまりを見つけよう','問題：たし算・ひき算・かけ算をどのように考えるか','見通し：数直線・テープ図・九九表から考える','考えの交流：式の意味と計算の工夫を比べる','まとめ：見つけたきまりを言葉と式で表す'];
  const secondGradeMathLesson=['導入：既習の数や計算を振り返り、本時の問題をつかむ','自力解決：図・数直線・式・九九表を使って考える','交流：考え方と式の意味を説明し合う','整理：共通するきまりや計算の工夫をまとめる','評価・振り返り：類題で考え方を使えるか確かめる'];
  const thirdGradeMathBoard=['めあて：図や表を使って、数量の関係を説明しよう','問題：どの計算や表し方を使えばよいか','見通し：数直線・表・図・式から考える','考えの交流：計算の仕方や表の読み取りを比べる','まとめ：きまりを式や言葉で説明する'];
  const thirdGradeMathLesson=['導入：既習の計算や数量の見方を振り返る','自力解決：図・表・式を使って問題を解決する','交流：考え方の共通点と違いを説明する','整理：計算や数量のきまりを言葉でまとめる','評価・振り返り：新しい問題に考え方を使う'];
  const fourthGradeMathBoard=['めあて：数量や図形の関係を、図・式・言葉で説明しよう','問題：どの数量に着目すれば解決できるか','見通し：表・数直線・図・式を使う方法を考える','考えの交流：解き方の共通点と違いを比べる','まとめ：きまりや計算方法を一般化する'];
  const fourthGradeMathLesson=['導入：既習の数量・図形・計算を振り返る','自力解決：表・数直線・図・式を選んで考える','交流：考え方の根拠と式の意味を説明する','整理：きまりや計算方法を整理して表す','評価・振り返り：別の問題に方法を適用する'];
  const sixthGradeMathBoard=['めあて：数量や図形の関係を、式と図で説明しよう','問題：どの数量・関係に着目すればよいか','見通し：比・数直線・図・表から考える','考えの交流：複数の解き方を比べ、一般化する','まとめ：中学校の数学につながる見方・考え方'];
  const sixthGradeMathLesson=['導入：既習事項と中学校につながる課題を確認する','自力解決：式・図・表・グラフを選んで考える','交流：解決の根拠と数量関係を説明し合う','整理：考え方を一般化し、別の場面へ広げる','評価・振り返り：学んだ見方を今後の学習に結び付ける'];
  function mathUnitRows(type){ const u=state.unit||''; const sets=[
    {test:/割合/,board:['めあて：割合を数直線と式で説明しよう','中心問題：120円の20%は何円？','数直線：もとにする量100%・割合20%・比べる量□','考えの交流：120×0.2、120×20÷100を比べる','まとめ：比べる量＝もとにする量×割合'],lesson:['導入：割引や男女の人数など身近な割合を提示','自力解決：もとにする量・割合・比べる量を見付ける','交流：数直線と式を使った考えを比較する','整理：3つの量の関係を式にまとめる','評価・振り返り：割合を使って別の問題を解く']},
    {test:/わり算/,board:['めあて：わり算の意味を図と式で説明しよう','中心問題：24個を6人で同じ数ずつ分けると？','図：24個のまとまりを6つに分ける／6ずつ囲む','考えの交流：等分除と包含除の場面を比べる','まとめ：わり算は同じ数ずつ分ける・何倍分かを求める'],lesson:['導入：同じ数ずつ分ける場面を操作する','自力解決：図や具体物で分け方を表す','交流：式の数が何を表すか説明する','整理：等分除・包含除の意味を整理する','評価・振り返り：場面に合う式を選ぶ']},
    {test:/かけ算|九九/,board:['めあて：かけ算のきまりを見つけよう','中心問題：4人分の3個ずつは全部で何個？','図：同じ数のまとまりを並べ、3×4と4×3を比較','考えの交流：交換法則や九九のきまりを見付ける','まとめ：同じ数のまとまりは、かけ算で表せる'],lesson:['導入：同じ数ずつ並ぶ場面を提示','自力解決：絵・たし算・かけ算で表す','交流：かける数とかけられる数の意味を説明する','整理：九九や交換法則のきまりを整理する','評価・振り返り：身近な場面をかけ算で表す']},
    {test:/面積/,board:['めあて：面積の求め方を図と式で説明しよう','中心問題：長方形の広さはどう求められる？','図：1cm²の正方形を並べ、たて×よこの関係を確認','考えの交流：分ける・移す・公式を使う方法を比べる','まとめ：長方形の面積＝たて×よこ'],lesson:['導入：広さを比べる活動を行う','自力解決：単位正方形を敷き詰めて数える','交流：たてとよこに分けて数える方法を説明する','整理：面積の単位と公式をまとめる','評価・振り返り：複合図形の面積に広げる']},
    {test:/角の大きさ|角度/,board:['めあて：角の大きさを分度器で測ろう','中心問題：この角は何度？どこから測る？','図：0度の線を辺に合わせ、中心と目盛りを確認','考えの交流：内側・外側の目盛りの読み方を比べる','まとめ：角の大きさは辺の開きで、度で表す'],lesson:['導入：開き方の違う角を比べる','自力解決：分度器の中心と0度の線を合わせる','交流：測り方の手順を説明する','整理：角度の単位と180度・360度を確認する','評価・振り返り：角を作図・測定する']},
    {test:/分数/,board:['めあて：分数の大きさと計算の意味を考えよう','中心問題：同じ大きさを分数でどう表す？','図：テープ図を等分し、分母と分子の意味を確認','考えの交流：数直線上の位置と大きさを比べる','まとめ：分数は1を等分したいくつ分かを表す'],lesson:['導入：1を等分する場面を作る','自力解決：テープ図や数直線で分数を表す','交流：分母・分子の意味を説明する','整理：同分母の加減や大きさの比べ方をまとめる','評価・振り返り：生活場面の分数を見付ける']},
    {test:/比例/,board:['めあて：2つの量の変わり方を表と式で説明しよう','中心問題：水の量が2倍、3倍になると重さは？','表：対応する2つの量を並べ、増え方を比べる','考えの交流：比例する関係を式とグラフで比べる','まとめ：一方が2倍・3倍になると、もう一方も同じ倍になる'],lesson:['導入：伴って変わる2つの量を提示','自力解決：表を作り、対応のきまりを探す','交流：式・表・グラフの表し方を比較する','整理：比例の意味と活用方法をまとめる','評価・振り返り：身近な比例の場面を説明する']},
    {test:/小数/,board:['めあて：小数の仕組みを位取り表で説明しよう','中心問題：0.1が何個で1になる？','位取り表：一の位・十分の一・百分の一を並べる','考えの交流：数直線と位取り表で大きさを比べる','まとめ：小数は10分の1を単位にして表す'],lesson:['導入：1より小さい量を測る場面を提示','自力解決：位取り表や数直線で表す','交流：小数の各位の意味を説明する','整理：小数の加減乗除の仕組みをまとめる','評価・振り返り：小数を使う生活場面を解く']}
  ]; const found=sets.find(x=>x.test.test(u)); if(found)return type==='board'?found.board:found.lesson; const label=u||'この単元'; return type==='board'?[`めあて：${label}の考え方を図・式・言葉で説明しよう`,`中心問題：${label}で大切な数量や図形は何だろう`,`見通し：既習の図・表・式から使えそうな方法を選ぶ`,`考えの交流：${label}の考え方を比べ、共通点を見つける`,`まとめ：${label}で使えるきまりを自分の言葉で整理する`]:[`導入：${label}につながる身近な場面を提示`,`自力解決：${label}の問題を図・式・言葉で考える`,`交流：考え方の根拠と表し方を説明し合う`,`整理：${label}のきまりや手順を板書で整理する`,`評価・振り返り：別の問題に${label}の考え方を使う`]; }
  function subjectUnitRows(type){ const u=state.unit||''; const sets={
    '国語':[
      {test:/物語|読み取り/,board:['めあて：登場人物の気持ちを本文の言葉から考えよう','中心場面：心情が変化した出来事を確認','本文の言葉：気持ちが分かる表現に線を引く','考えの交流：同じ場面・違う場面の根拠を比べる','まとめ：本文の言葉を根拠に気持ちを説明する'],lesson:['導入：物語の場面と本時の問いを確認する','読解：心情や出来事を表す本文の言葉を探す','交流：根拠を示して人物の気持ちを説明する','整理：出来事と心情の変化をつなげる','評価・振り返り：本文を根拠に読めたか確かめる']},
      {test:/漢字/,board:['めあて：漢字の形・音・意味を結び付けよう','中心問題：この漢字はどんな場面で使う？','部首・音・意味：仲間の漢字を集める','言葉づくり：熟語や文で使い方を比べる','まとめ：正しい読み方・書き方・使い方'],lesson:['導入：既習漢字と新しい漢字を比べる','確認：部首・音・意味・書き順を確かめる','活動：熟語や短文を作って使う','交流：使い方や間違いやすい点を伝える','評価・振り返り：文の中で正しく使う']},
      {test:/説明文|要旨/,board:['めあて：段落の役割と筆者の考えを整理しよう','中心問題：文章で一番伝えたいことは何？','段落構成：問い・説明・まとめを色分けする','根拠の交流：大事な言葉と要旨を比べる','まとめ：段落の関係をつなげて要旨を書く'],lesson:['導入：題名・写真・段落から問いをもつ','読解：中心となる言葉と段落の役割を探す','交流：要旨の根拠を本文から説明する','整理：段落相互の関係を図に表す','評価・振り返り：要旨を短くまとめる']}
    ],
    '理科':[
      {test:/天気/,board:['問題：天気の変化にはどんなきまりがある？','予想：雲の動きと天気を予想する','観察：時刻・雲の量・形・風向きを記録','結果・考察：観察結果を表や写真で比べる','まとめ：雲の動きと天気の変化を説明する'],lesson:['導入：空の様子を観察し問題をつくる','予想：天気の変化と雲の様子を予想する','観察：同じ時刻・場所で継続して記録する','考察：記録を並べ、変化の関係を考える','評価・振り返り：観察事実を根拠に説明する']},
      {test:/発芽|植物/,board:['問題：植物が発芽するには何が必要？','予想：水・空気・温度の条件を考える','実験：変える条件とそろえる条件を表にする','結果・考察：発芽した種としない種を比べる','まとめ：発芽に必要な条件を説明する'],lesson:['導入：種子の変化を観察する','予想：発芽に必要な条件を理由とともに考える','実験：条件を一つずつ変えて比較する','考察：結果を表に整理し条件を判断する','評価・振り返り：実験の条件設定を振り返る']},
      {test:/電流|磁力/,board:['問題：電流がつくる磁力にはどんな性質がある？','予想：電池の向き・電流の強さと磁力を考える','実験：コイル・電池・方位磁針の条件を整理','結果・考察：電流の向きや大きさで比べる','まとめ：電流と磁力の関係を説明する'],lesson:['導入：電磁石の働きを身近な道具から考える','予想：条件を変えたときの磁力を予想する','実験：安全に回路を組み、結果を記録する','考察：条件と磁力の変化を関連付ける','評価・振り返り：実験結果から性質を説明する']}
    ],
    '社会':[
      {test:/国土/,board:['めあて：日本の国土の特色を資料から説明しよう','問い：日本の地形・気候にはどんな特色がある？','資料：地図・写真・雨温図から事実を拾う','比較：地域ごとの違いと暮らしを比べる','まとめ：国土の特色と人々の生活を説明する'],lesson:['導入：地図や写真から疑問をもつ','資料活用：地形・気候の資料を読み取る','比較：地域ごとの特色を表に整理する','説明：資料を根拠に暮らしとの関係を考える','評価・振り返り：国土の特色を説明する']},
      {test:/食料/,board:['めあて：食料生産を支える人々の工夫を考えよう','問い：どこで、何を、どのように作っている？','資料：産地・生産量・運輸の資料を読む','比較：地域や生産方法の違いを比べる','まとめ：食料生産と私たちの生活をつなげる'],lesson:['導入：給食や食品の産地から問いをもつ','調査：地図・統計・写真から事実を集める','整理：生産の工夫と課題を関係付ける','交流：資料を根拠に考えを説明する','評価・振り返り：食料生産の意味を考える']},
      {test:/工業/,board:['めあて：工業生産を支える仕組みを説明しよう','問い：工場はどこで何を工夫している？','資料：工業地域・製品・輸送の資料を整理','比較：原料・技術・輸送のつながりを比べる','まとめ：工業生産と人々の生活の関係'],lesson:['導入：身近な製品から疑問をもつ','資料活用：工業地域と生産工程を調べる','整理：原料・製造・輸送・販売をつなげる','交流：工夫や課題を資料を根拠に説明する','評価・振り返り：工業生産の役割をまとめる']}
    ],
    '英語':[
      {test:/自己紹介/,board:['めあて：自分のことを相手に伝えよう','表現：I am ～.／I like ～.／My name is ～.','モデル：教師と児童のやり取りを聞く','活動：名前・好きなものをペアで伝え合う','まとめ：相手を見て、聞こえる声で伝える'],lesson:['導入：自己紹介の場面と表現を聞く','練習：名前・好きなものの音と意味を確認する','活動：ペアで自己紹介を伝え合う','共有：伝わった工夫や聞き返しを振り返る','評価・振り返り：相手意識をもって話せたか確認する']},
      {test:/道案内/,board:['めあて：場所や道順を英語で伝えよう','表現：Go straight.／Turn left.／It is next to ～.','モデル：地図を使った道案内を聞く','活動：ペアで目的地まで案内する','まとめ：相手の反応を見て伝え方を工夫する'],lesson:['導入：学校や町の地図から場面を設定する','練習：方向・場所の表現を聞いて言う','活動：地図を使い道順を伝え合う','共有：分かりやすい伝え方を比べる','評価・振り返り：伝わる順序と表現を使えたか確認する']},
      {test:/ものの名前/,board:['めあて：身の回りのものを英語で伝えよう','表現：This is ～.／I have ～.','モデル：絵カードと音声を結び付ける','活動：友だちに質問し、ものの名前を伝える','まとめ：聞く・話すときの相手意識を確認する'],lesson:['導入：身近なものの写真や実物を提示する','練習：ものの名前と表現を聞いて発音する','活動：絵カードを使って質問と応答をする','共有：伝わりやすい声やリズムを確認する','評価・振り返り：学んだ表現を使って伝える']}
    ]
  }; const list=sets[state.subject]||[]; const found=list.find(x=>x.test.test(u)); if(found)return type==='board'?found.board:found.lesson; const label=u||'この単元'; return type==='board'?[`めあて：${label}の大切な考え方を説明しよう`,`中心問題：${label}で何に着目すればよいだろう`,`資料・活動：${label}に必要な言葉・図・資料を整理`,`交流：${label}について根拠を示して考えを比べる`,`まとめ：${label}で分かったことを自分の言葉で整理する`]:[`導入：${label}につながる身近な場面を提示`,`活動：${label}の資料・言葉・実験・会話を使って考える`,`交流：根拠を示して考えを伝え合う`,`整理：${label}の大切な内容を板書で構造化する`,`評価・振り返り：${label}でできたことと次の課題を確認する`]; }
  function getSupportRows(type){ if(state.subject==='算数')return mathUnitRows(type); return subjectUnitRows(type); }
  function renderSupportResult(type){ const isBoard=type==='board'; const title=isBoard?'板書例':'授業指導案'; const rows=getSupportRows(type); const box=el('.panel'); if(!box)return; let old=el('#support-result'); if(!old){old=document.createElement('div');old.id='support-result';old.className='support-result';box.appendChild(old);} old.innerHTML=`<div class="result"><h3>${state.grade} ${state.subject}「${state.unit}」${title}</h3><p class="source-note">${isBoard?'教科の学び方に合わせて、ねらい・中心資料・考えの交流・まとめが見える板書構成です。':'単元の目標・学習活動・教師の支援・評価がつながる授業指導案の構成です。'}</p><div class="support-paper">${rows.map((x,i)=>`<div class="support-row"><b>${i+1}</b><span>${x}</span></div>`).join('')}</div><div class="actions"><button class="primary" id="print-support" data-support-type="${type}">印刷</button><button class="secondary" id="save-support" data-support-type="${type}">マイ授業デスクに保存</button></div></div>`; if(isBoard)addBoardVisual(); }
  function render(){ state.page==='home'?renderHome():state.page==='desk'?renderDesk():renderDetail(); renderSupportDesk(); applyLabels(); normalizeLessonLabels(); ensureTabBackButton(); }
  document.addEventListener('click', e=>{ const t=e.target.closest('button'); if(!t)return; if(t.dataset.page){state.page=t.dataset.page;document.querySelectorAll('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.page===state.page));render();return;} if(t.dataset.grade){state.grade=t.dataset.grade;state.unit=selectedUnits()[0]||units[state.subject][0];render();return;} if(t.dataset.subject){state.subject=t.dataset.subject;state.unit=selectedUnits()[0]||units[state.subject][0];render();return;} if(t.dataset.unit){state.unit=t.dataset.unit;render();return;} if(t.dataset.level){state.level=t.dataset.level;render();return;} if(t.dataset.demo){renderSupportResult(t.dataset.demo);return;} if(t.id==='generate-test'||t.id==='regenerate-test'){state.result={items:buildItems()};renderTestResult();return;} if(t.id==='generate-worksheet'||t.id==='regenerate-worksheet'){state.worksheetResult=buildWorksheet();renderWorksheetResult();applyLabels();return;} if(t.id==='generate-pack'){state.result={items:buildItems()};state.worksheetResult=buildWorksheet();renderPackResult();return;} if(t.id==='print-support'){printSupport();return;} if(t.id==='save-support'){saveSupport(t.dataset.supportType);return;} if(t.id==='delete-support'){const items=loadSupportSaved();items.splice(Number(t.dataset.deleteSupport),1);localStorage.setItem('schoolpilot-support-materials',JSON.stringify(items));render();return;} if(t.id==='copy-test'){copyText();return;} if(t.id==='copy-worksheet'){copyWorksheet();return;} if(t.id==='print-worksheet'||t.id==='save-worksheet-pdf'){printWorksheet();return;} if(t.id==='save-worksheet-desk'){saveWorksheetToDesk();return;} if(t.dataset.renameSaved){renameSaved(t.dataset.renameStore,Number(t.dataset.renameSaved));return;} if(t.dataset.deleteSaved){deleteSaved(t.dataset.deleteStore,Number(t.dataset.deleteSaved));return;} if(t.id==='save-desk'){if(saveToDesk())showMessage('マイ授業デスクに保存しました。');return;} if(t.id==='save-local-pdf'){printTestPdf();return;} if(t.dataset.openSaved){const store=t.dataset.openStore||'test';const items=store==='review'?loadReviewSaved():loadSaved();const x=items[Number(t.dataset.openSaved)];if(x){Object.assign(state,x,{publisher:x.publisher||state.publisher,page:'detail',activeTab:'test'});render();if(store==='review'){state.worksheetResult={items:x.items};renderWorksheetResult();}else{state.result={items:x.items};renderTestResult();}}return;} });
  document.addEventListener('click', e=>{ const t=e.target.closest('[data-publisher]'); if(!t)return; state.publisher=t.dataset.publisher; state.unit=selectedUnits()[0]||units[state.subject][0]; render(); });
  document.addEventListener('click', e=>{ const t=e.target.closest('[data-search]'); if(!t||t.disabled)return; state.page='detail'; state.activeTab='overview'; history.pushState({schoolpilot:true,page:'detail',from:'home'},'',`${location.pathname}${location.search}#detail`); render(); });
  document.addEventListener('click', e=>{ const t=e.target.closest('[data-back]'); if(!t)return; if(history.state&&history.state.schoolpilot&&history.state.page==='detail'){history.back();}else{state.page='home';render();} });
  window.addEventListener('popstate',()=>{ if(history.state&&history.state.schoolpilot){state.page=history.state.page||'home';render();}else{state.page='home';render();} });
  document.addEventListener('click', e=>{ const t=e.target.closest('[data-return-support]'); if(!t)return; state.page='detail'; state.activeTab=t.dataset.returnSupport==='board'?'board':'lesson'; render(); });
  document.addEventListener('click', e=>{ const t=e.target.closest('[data-open-support]'); if(!t)return; const x=loadSupportSaved()[Number(t.dataset.openSupport)]; if(!x)return; Object.assign(state,{grade:x.grade,subject:x.subject,unit:x.unit,level:x.level,page:'detail',activeTab:x.type==='board'?'board':'lesson'}); render(); renderSupportResult(x.type); });
  document.addEventListener('click',e=>{const t=e.target.closest('[data-delete-support]');if(!t)return;const items=loadSupportSaved();items.splice(Number(t.dataset.deleteSupport),1);localStorage.setItem('schoolpilot-support-materials',JSON.stringify(items));render();});
  document.addEventListener('click',e=>{const t=e.target.closest('[data-demo="board"]');if(t){setTimeout(addBoardVisual,0);}});
  document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){state.activeTab=tab.dataset.tab;renderActiveTab();normalizeLessonLabels();ensureTabBackButton();return;}const minutes=e.target.closest('[data-minutes]');if(minutes){state.lessonMinutes=Number(minutes.dataset.minutes);renderActiveTab();normalizeLessonLabels();ensureTabBackButton();}});
  document.addEventListener('click',e=>{const lesson=e.target.closest('[data-demo="lesson"]');if(lesson){setTimeout(()=>{const rows=document.querySelectorAll('#support-result .support-row');const count=state.lessonMinutes===15?3:state.lessonMinutes===30?5:6;rows.forEach((r,i)=>{if(i>=count)r.remove();});},0);}});
  if(!history.state||!history.state.schoolpilot)history.replaceState({schoolpilot:true,page:'home'},'',`${location.pathname}${location.search}#home`);
  render();
})();
