(() => {
  'use strict';
  const STORAGE_KEY = 'sensei-jitan-v12-tests';
  const state = { page: 'home', grade: '5年', subject: '算数', publisher: '東京書籍', unit: '割合', level: '標準', result: null, worksheetResult: null, activeTab: 'overview', lessonMinutes: 45 };
  const app = document.getElementById('app');
  const subjects = ['国語', '算数', '理科', '社会', '英語'];
  const units = { 国語: ['物語文の読み取り', '漢字の広場', '説明文の要旨'], 算数: ['割合', '小数のかけ算', '図形の面積'], 理科: ['天気の変化', '植物の発芽', '電流がつくる磁力'], 社会: ['日本の国土', '食料生産', '工業生産'], 英語: ['自己紹介', '道案内', 'ものの名前'] };
  const levels = ['やさしい', '標準', 'チャレンジ', '特別支援配慮'];
  const gradeOptions = ['1年', '2年', '3年', '4年', '5年', '6年'];
  const publishers = ['東京書籍', '大日本図書', '学校図書', '教育出版', '啓林館', '日本文教出版'];
  const textbookUnits = {
    '5年|算数|東京書籍': ['整数と小数', '直方体や立方体の体積', '比例', '小数のかけ算', '小数のわり算', '合同な図形', '図形の角', '偶数と奇数・倍数と約数', '分数と小数・整数の関係', '分数のたし算とひき算', '平均', '単位量あたりの大きさ', '四角形と三角形の面積', '割合', '帯グラフと円グラフ', '変わり方調べ', '正多角形と円周の長さ', '角柱と円柱'],
    '5年|算数|大日本図書': ['整数と小数', '体積', '小数のかけ算', '小数のわり算', '合同な図形', '図形の角', '偶数と奇数・倍数と約数', '分数と小数', '分数のたし算とひき算', '平均', '単位量あたりの大きさ', '図形の面積', '割合', '帯グラフと円グラフ', '変わり方', '正多角形と円周', '角柱と円柱'],
    '5年|算数|学校図書': ['整数と小数', '体積', '小数のかけ算', '小数のわり算', '合同な図形', '図形の角', '倍数と約数', '分数', '平均', '単位量あたりの大きさ', '図形の面積', '割合', '帯グラフと円グラフ', '変わり方', '正多角形と円周', '角柱と円柱'],
    '5年|算数|教育出版': ['整数と小数', '体積', '小数のかけ算', '小数のわり算', '合同な図形', '図形の角', '倍数と約数', '分数のたし算とひき算', '平均', '単位量あたりの大きさ', '図形の面積', '割合', '帯グラフと円グラフ', '変わり方', '正多角形と円周', '角柱と円柱'],
    '5年|算数|啓林館': ['整数と小数', '体積', '比例', '小数のかけ算', '小数のわり算', '合同な図形', '図形の角', '整数の性質', '分数のたし算とひき算', '平均', '単位量あたりの大きさ', '図形の面積', '割合', '帯グラフと円グラフ', '変わり方', '正多角形と円周', '角柱と円柱'],
    '5年|算数|日本文教出版': ['整数と小数', '体積', '小数のかけ算', '小数のわり算', '合同な図形', '図形の角', '整数の性質', '分数', '平均', '単位量あたりの大きさ', '図形の面積', '割合', '帯グラフと円グラフ', '変わり方', '正多角形と円周', '角柱と円柱']
  };
  function selectedUnits(){ return textbookUnits[`${state.grade}|${state.subject}|${state.publisher}`] || units[state.subject]; }
  const researchBasis = '<div class="source-note">出題の参考（公開教材の構成を参考にした類題）：<a href="https://surapuri.jp/elementary_school05/wariai/" target="_blank" rel="noopener">すらぷり</a> ／ <a href="https://happylilac.net/keisan-wariai.html" target="_blank" rel="noopener">ちびむすドリル</a> ／ <a href="https://www.print365.net/kurabekatabunsyo5nen/" target="_blank" rel="noopener">ぷりんと365</a> ／ <a href="https://www.mext.go.jp/component/a_menu/education/micro_detail/__icsFiles/afieldfile/2009/06/16/1234931_004_1.pdf" target="_blank" rel="noopener">文部科学省</a></div>';
  const testSets = {
    '5年|算数|割合': [
      { format: '選択式', question: '120円の20%はいくらですか。', choices: ['12円', '24円', '60円', '100円'], answer: '24円', explain: '20%は100分の20です。120×0.2＝24なので、24円です。' },
      { format: '短答', question: '45人のうち女子が18人でした。女子は全体の何%ですか。', answer: '40%', explain: '18÷45＝0.4。0.4を百分率にすると40%です。' },
      { format: '説明問題', question: '定価800円の30%引きの値段を求める方法を説明しましょう。', answer: '800×(1−0.3)＝560円', explain: '30%引きは、もとの70%の値段になるという意味です。800×0.7で560円です。' },
      { format: '選択式', question: 'もとにする量が50、比べる量が15のとき、割合はどれですか。', choices: ['15%', '30%', '50%', '65%'], answer: '30%', explain: '割合は比べる量÷もとにする量。15÷50＝0.3なので30%です。' },
      { format: '短答', question: 'ある数の25%が10です。ある数はいくつですか。', answer: '40', explain: '25%は0.25なので、10÷0.25＝40です。' }
    ]
  };
  const genericTemplates = {
    国語: [{format:'短答',question:'文章の大事な内容を一文でまとめるとき、何に注目しますか。',answer:'中心となる話題と筆者の考え',explain:'くり返し出てくる言葉や段落の中心を探すと、要点を見つけやすくなります。'},{format:'選択式',question:'段落の役割として近いものを選びましょう。',choices:['話題を示す','計算する','地図を読む','実験する'],answer:'話題を示す',explain:'最初の段落には、これから何について書くかを示す役割があります。'}],
    算数: [{format:'短答',question:'この単元で使う大切な式を書きましょう。',answer:'比べる量÷もとにする量＝割合',explain:'割合は、比べる量がもとにする量のどれだけかを表します。'},{format:'選択式',question:'答えを確かめるときに大切なことはどれですか。',choices:['単位や大きさを見る','色だけを見る','速く書く','答えを隠す'],answer:'単位や大きさを見る',explain:'単位や答えの大きさが問題に合っているか確かめます。'}],
    理科: [{format:'選択式',question:'観察するときに記録するとよいものはどれですか。',choices:['日時や変化','好きな色だけ','友達の名前だけ','予想しない'],answer:'日時や変化',explain:'日時と変化を記録すると、結果を比べて考えられます。'},{format:'説明問題',question:'予想を立ててから実験するよさを説明しましょう。',answer:'結果を予想と比べて考えられること',explain:'予想と結果の違いに目を向けると、きまりを見つけやすくなります。'}],
    社会: [{format:'短答',question:'地図で方位を表す基本の4方向を書きましょう。',answer:'東・西・南・北',explain:'地図では方位を使うと、場所の関係を正確に表せます。'},{format:'選択式',question:'資料を読むとき最初に確かめるものはどれですか。',choices:['題名や単位','色の好み','紙の大きさ','文字の形'],answer:'題名や単位',explain:'題名と単位を確かめると、資料が何を表すか分かります。'}],
    英語: [{format:'短答',question:'「私は〜です」と自己紹介するときの表現を書きましょう。',answer:'I am 〜.',explain:'I amは「私は〜です」という意味の表現です。'}]
  };
  function el(selector){ return document.querySelector(selector); }
  function renderHome(){ app.innerHTML = `<section class="hero"><div class="eyebrow">SCHOOLPILOT</div><h1>今日は何を準備しますか？</h1><p>学年と教科を選ぶだけで、授業準備に使える素材をすぐに作れます。</p></section><div class="section-title"><h2>学年を選ぶ</h2><p>まずは対象学年を選択</p></div><div class="grade-grid">${gradeOptions.map(g=>`<button class="choice ${g===state.grade?'selected':''}" data-grade="${g}"><strong>${g}</strong><span>授業素材を探す</span></button>`).join('')}</div><div class="section-title"><h2>教科を選ぶ</h2><p>${state.grade}の単元</p></div><div class="subject-grid">${subjects.map(s=>`<button class="choice ${s===state.subject?'selected':''}" data-subject="${s}"><strong>${s}</strong><span>${units[s].length}単元</span></button>`).join('')}</div><div class="section-title"><h2>単元を選ぶ</h2><p>単元詳細から素材を使えます</p></div><div class="unit-grid">${units[state.subject].map(u=>`<button class="unit-card" data-unit="${u}"><strong>${u}</strong><span>授業案・板書・小テスト・復習テスト</span></button>`).join('')}</div>`; }
  function renderHome(){ app.innerHTML = `<section class="hero"><div class="eyebrow">SCHOOLPILOT</div><h1>授業準備教材を探す</h1><p>学年・教科・教科書出版社を選ぶと、対応する単元を表示します。</p></section><div class="section-title"><h2>学年を選ぶ</h2></div><div class="grade-grid">${gradeOptions.map(g=>`<button class="choice ${g===state.grade?'selected':''}" data-grade="${g}"><strong>${g}</strong></button>`).join('')}</div><div class="section-title"><h2>教科を選ぶ</h2></div><div class="subject-grid">${subjects.map(s=>`<button class="choice ${s===state.subject?'selected':''}" data-subject="${s}"><strong>${s}</strong></button>`).join('')}</div><div class="section-title"><h2>教科書の出版社を選ぶ</h2><p>${state.grade}・${state.subject}</p></div><div class="publisher-grid">${publishers.map(p=>`<button class="choice ${p===state.publisher?'selected':''}" data-publisher="${p}"><strong>${p}</strong></button>`).join('')}</div><p class="publisher-note">単元一覧は、文部科学省の教科書制度および各出版社の公開資料を参考に同梱しています。学校の採択版・年度によって配列や名称が異なる場合があります。</p><div class="section-title"><h2>単元を選ぶ</h2><p>${state.publisher}の公開単元配列を参考</p></div><div class="unit-grid">${selectedUnits().map(u=>`<button class="unit-card" data-unit="${u}"><strong>${u}</strong></button>`).join('')}</div>`; }
  function renderHome(){ const unitList=selectedUnits(); const ready=Boolean(state.grade&&state.subject&&state.publisher&&state.unit); app.innerHTML = `<section class="hero"><div class="eyebrow">SCHOOLPILOT</div><h1>授業準備教材を探す</h1><p>学年・教科・教科書出版社・単元を選んでください。</p></section><div class="section-title"><h2>学年を選ぶ</h2></div><div class="grade-grid">${gradeOptions.map(g=>`<button class="choice ${g===state.grade?'selected':''}" data-grade="${g}"><strong>${g}</strong></button>`).join('')}</div><div class="section-title"><h2>教科を選ぶ</h2></div><div class="subject-grid">${subjects.map(s=>`<button class="choice ${s===state.subject?'selected':''}" data-subject="${s}"><strong>${s}</strong></button>`).join('')}</div><div class="section-title"><h2>教科書の出版社を選ぶ</h2><p>${state.grade}・${state.subject}</p></div><div class="publisher-grid">${publishers.map(p=>`<button class="choice ${p===state.publisher?'selected':''}" data-publisher="${p}"><strong>${p}</strong></button>`).join('')}</div><p class="publisher-note">単元一覧は、文部科学省の教科書制度および各出版社の公開資料を参考に同梱しています。学校の採択版・年度によって配列や名称が異なる場合があります。</p><div class="section-title"><h2>単元を選ぶ</h2><p>${state.publisher}の公開単元配列を参考</p></div><div class="unit-grid">${unitList.map(u=>`<button class="unit-card ${u===state.unit?'selected':''}" data-unit="${u}"><strong>${u}</strong></button>`).join('')}</div><div class="home-search"><button class="primary search-button" data-search ${ready?'':'disabled'}>検索</button>${ready?'':'<p class="search-note">学年・教科・出版社・単元をすべて選択してください。</p>'}</div>`; }
  function loadReviewSaved(){ try{return JSON.parse(localStorage.getItem('schoolpilot-review-tests')||'[]');}catch(e){return [];} }
  function loadSupportSaved(){ try{return JSON.parse(localStorage.getItem('schoolpilot-support-materials')||'[]');}catch(e){return [];} }
  function renderDesk(){ const tests=loadSaved(), reviews=loadReviewSaved(); const cards=(items,kind,offset,store)=>items.map((x,i)=>`<article class="desk-card"><h3>${x.title||`${x.grade} ${x.subject}「${x.unit}」`}</h3><p>${kind} / ${x.level} / ${x.items.length}問</p><div class="actions"><button class="secondary" data-open-saved="${offset+i}" style="margin-top:12px">開く</button><button class="secondary" data-rename-saved="${i}" data-rename-store="${store}" style="margin-top:12px">名前変更</button><button class="danger" data-delete-saved="${i}" data-delete-store="${store}" style="margin-top:12px">削除</button></div></article>`).join(''); app.innerHTML = `<section class="hero"><div class="eyebrow">MY TEACHING DESK</div><h1>マイ授業デスク</h1><p>小テストと復習テストの保存データを、それぞれのカテゴリで確認できます。</p></section><div class="desk-category"><div class="section-title"><h2>小テスト</h2><p>${tests.length}件</p></div>${tests.length?`<div class="desk-grid">${cards(tests,'小テスト',0,'test')}</div>`:'<div class="empty">小テストの保存データはありません。</div>'}</div><div class="desk-category"><div class="section-title"><h2>復習テスト</h2><p>${reviews.length}件</p></div>${reviews.length?`<div class="desk-grid">${cards(reviews,'復習テスト',tests.length,'review')}</div>`:'<div class="empty">復習テストの保存データはありません。</div>'}</div>`; }
  function deleteSaved(store,index){ const key=store==='review'?'schoolpilot-review-tests':STORAGE_KEY; const items=store==='review'?loadReviewSaved():loadSaved(); if(!items[index])return; if(!window.confirm('この保存データを削除しますか？'))return; items.splice(index,1); localStorage.setItem(key,JSON.stringify(items)); render(); }
  function renderSupportDesk(){ if(state.page!=='desk'||!el('.container')||el('#support-desk-category'))return; const items=loadSupportSaved(); const box=document.createElement('div');box.id='support-desk-category';box.className='desk-category';box.innerHTML=`<div class="section-title"><h2>指導案・板書例</h2><p>${items.length}件</p></div>${items.length?`<div class="desk-grid">${items.map((x,i)=>`<article class="desk-card"><h3>${x.title}</h3><p>${x.level} / ${x.type==='board'?'板書例':'指導案・授業展開例'}</p><button class="danger" data-delete-support="${i}" style="margin-top:12px">削除</button></article>`).join('')}</div>`:'<div class="empty">保存した指導案・板書例はありません。</div>'}`;el('.container').appendChild(box); }
  function renameSaved(store,index){ const key=store==='review'?'schoolpilot-review-tests':STORAGE_KEY; const items=store==='review'?loadReviewSaved():loadSaved(); if(!items[index])return; const current=items[index].title||`${items[index].grade} ${items[index].subject}「${items[index].unit}」`; const title=window.prompt('保存名を入力してください。',current); if(title===null||!title.trim())return; items[index].title=title.trim(); localStorage.setItem(key,JSON.stringify(items)); render(); }
  function renderDetail(){ app.innerHTML = `<div class="crumbs">ホーム / ${state.grade} / ${state.subject}</div><section class="panel"><div class="unit-head"><div><span class="pill">${state.grade}・${state.subject}</span><h1>「${state.unit}」</h1></div><button class="secondary" data-page="home">単元一覧に戻る</button></div><div class="tabs"><button class="tab active">単元概要</button><button class="tab">45分授業案</button><button class="tab">AI板書</button><button class="tab active">AIミニテスト</button></div><p class="notice">授業レベルを選び、必要な素材のボタンを押してください。MVPではブラウザ内テンプレートから生成します。</p><div class="levels">${levels.map(l=>`<button class="level ${l===state.level?'selected':''}" data-level="${l}">${l}</button>`).join('')}</div><div class="feature"><h2>AI授業案生成 MVP</h2><p>学習目標・授業の流れ・発問・つまずき対応をまとめます。</p><div class="actions"><button class="secondary" data-demo="lesson">45分授業案を生成</button><button class="secondary" data-demo="board">板書案を生成</button></div></div><div class="feature test"><h2>AIミニテスト生成 MVP</h2><p>約5問の選択式・短答・説明問題を、正答とやさしい解説つきで作成します。</p><div class="actions"><button class="primary" id="generate-test">ミニテストを生成</button></div><div id="test-result"></div></div><div class="feature"><h2>AIワークシート生成 MVP</h2><p>児童向けの問題プリントを5問作成します。名前欄つきで、そのまま印刷できます。</p><div class="actions"><button class="primary" id="generate-worksheet">ワークシートを生成</button></div><div id="worksheet-result"></div></div></section>`; }
  function renderDetail(){ app.innerHTML=`<div class="crumbs">ホーム / ${state.grade} / ${state.subject}</div><section class="panel"><div class="unit-head"><div><span class="pill">${state.grade}・${state.subject}</span><h1>「${state.unit}」</h1></div><button class="secondary" data-page="home">単元一覧に戻る</button></div><div class="tabs"><button class="tab" data-tab="overview">単元概要</button><button class="tab" data-tab="lesson">授業案</button><button class="tab" data-tab="board">板書</button><button class="tab" data-tab="test">テスト</button></div><div id="tab-content"></div></section>`; renderActiveTab(); }
  function clearGeneratedContent(){ document.querySelectorAll('#support-result,.pack').forEach(n=>n.remove()); state.result=null; state.worksheetResult=null; }
  function renderOverview(){ const pane=el('#tab-content'); if(!pane)return; const ratio=state.grade==='5年'&&state.subject==='算数'&&state.unit==='割合'; const purpose=ratio?'割合を、もとにする量を1とみたときの比べられる量の大きさとして理解し、割合・比べられる量・もとにする量の関係を数・式・数直線で説明できるようにする。':`${state.unit}の基礎的な知識と技能を身に付け、学んだ考え方を使って問題を解決し、理由を説明できるようにする。`; const knowledge=ratio?'割合の意味、百分率、小数との関係を理解している。':`${state.unit}の用語・きまり・基本的な方法を理解している。`; const thinking=ratio?'何をもとにする量とするかを判断し、数直線や式を使って考え方を説明している。':'図・式・言葉を使って考え方を表し、結果を振り返っている。'; const attitude='見通しをもって取り組み、友達の考えと比べながら自分の考えを修正・説明しようとしている。'; const result=ratio?'割合を小数や百分率で表し、割合・比べられる量・もとにする量を求める問題を解決できる。':'学習した内容を使って基本問題と活用問題を解き、学んだことを自分の言葉で振り返ることができる。'; pane.innerHTML=`<div class="overview-card"><span class="pill">指導要領・学習評価を参照</span><h2>単元の目的</h2><p>${purpose}</p><h2>評価の観点</h2><div class="evaluation-grid"><div><b>知識・技能</b><p>${knowledge}</p></div><div><b>思考・判断・表現</b><p>${thinking}</p></div><div><b>主体的に学習に取り組む態度</b><p>${attitude}</p></div></div><h2>学習後に期待する結果</h2><p>${result}</p><p class="source-note">参照：<a href="https://www.mext.go.jp/content/20211102-mxt_kyoiku02-100002607_04.pdf" target="_blank" rel="noopener">文部科学省 小学校学習指導要領解説 算数編</a> ／ <a href="https://www.mext.go.jp/b_menu/hakusho/nc/1415169.htm" target="_blank" rel="noopener">文部科学省 学習評価の通知</a></p></div>`; }
  function renderActiveTab(){ const pane=el('#tab-content'); if(!pane)return; clearGeneratedContent(); document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===state.activeTab)); const levelHtml=`<p class="notice">授業レベルを選び、選択した内容を作成してください。ブラウザ内テンプレートで生成します。</p><div class="levels">${levels.map(l=>`<button class="level ${l===state.level?'selected':''}" data-level="${l}">${l}</button>`).join('')}</div>`; if(state.activeTab==='overview'){pane.innerHTML=`<div class="feature"><h2>単元概要</h2><p>${state.grade} ${state.subject}「${state.unit}」の学習内容を確認し、授業案・板書・テストを準備できます。</p><div class="overview-points"><span>学習内容を整理</span><span>授業時間に合わせて設計</span><span>印刷・保存に対応</span></div></div>`;renderOverview();} else if(state.activeTab==='lesson'){pane.innerHTML=`${levelHtml}<div class="feature"><h2>授業案</h2><p>15分・30分・45分から授業時間を選び、${state.unit}の学習内容を段階的に扱います。</p><div class="minutes">${[15,30,45].map(m=>`<button class="level ${m===state.lessonMinutes?'selected':''}" data-minutes="${m}">${m}分</button>`).join('')}</div><div class="actions"><button class="primary" data-demo="lesson">授業案を作成</button></div></div>`;} else if(state.activeTab==='board'){pane.innerHTML=`${levelHtml}<div class="feature"><h2>板書</h2><p>めあて・問題・考え方・まとめを、黒板の流れに沿って整理します。</p><div class="actions"><button class="primary" data-demo="board">板書例を作成</button></div></div>`;} else {pane.innerHTML=`${levelHtml}<div class="feature test"><h2>小テスト</h2><p>約5問の問題と正答・やさしい解説を作成します。</p><div class="actions"><button class="primary" id="generate-test">小テストを生成</button></div><div id="test-result"></div></div><div class="feature"><h2>復習テスト</h2><p>小テストとは別の問題で、理解の定着を確認します。</p><div class="actions"><button class="primary" id="generate-worksheet">復習テストを生成</button></div><div id="worksheet-result"></div></div>`;} applyLabels(); renderPackSection(); }
  function loadSaved(){ try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');}catch(e){return [];} }
  function saveToDesk(){
    if(!state.result||!state.result.items){ showMessage('先にミニテストを生成してください。'); return false; }
    try{
      const all=loadSaved().filter(x=>!(x.grade===state.grade&&x.subject===state.subject&&x.unit===state.unit&&x.level===state.level));
      all.unshift({grade:state.grade,subject:state.subject,unit:state.unit,level:state.level,items:state.result.items,savedAt:new Date().toISOString()});
      localStorage.setItem(STORAGE_KEY,JSON.stringify(all.slice(0,20)));
      return true;
    }catch(e){ showMessage('保存できませんでした。ブラウザのプライベート設定をご確認ください。'); return false; }
  }
  function saveLocalFile(){
    if(!state.result||!state.result.items){ showMessage('先にミニテストを生成してください。'); return; }
    const payload={version:'v12',grade:state.grade,subject:state.subject,unit:state.unit,level:state.level,items:state.result.items,savedAt:new Date().toISOString()};
    const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});
    const url=URL.createObjectURL(blob); const link=document.createElement('a');
    link.href=url; link.download=`${state.grade}_${state.subject}_${state.unit}_ミニテスト.json`;
    document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url);
    showMessage('ローカル保存しました。JSONファイルをダウンロードしました。');
  }
  function buildItems(){ const key=`${state.grade}|${state.subject}|${state.unit}`; if(testSets[key]) return testSets[key]; const base=genericTemplates[state.subject]||genericTemplates.算数; return Array.from({length:5},(_,i)=>({...base[i%base.length],question:`${state.unit}：${base[i%base.length].question}`})); }
  function renderTestResult(){ const r=state.result; if(!r)return; const html=`<div class="result"><h3>${state.grade} ${state.subject}「${state.unit}」のミニテスト（${state.level}）</h3>${researchBasis}${r.items.map((q,i)=>`<article class="question"><div class="question-head"><span class="qno">${i+1}</span><span class="format">${q.format}</span></div><p><strong>${q.question}</strong></p>${q.choices?`<p>${q.choices.map((c,j)=>`${String.fromCharCode(65+j)}．${c}`).join('　')}</p>`:''}<p class="answer">正答：${q.answer}</p><p class="explain">やさしい解説：${q.explain}</p></article>`).join('')}<div class="actions"><button class="primary" id="regenerate-test">作り直す</button><button class="secondary" id="copy-test">コピー</button><button class="secondary" id="save-desk">マイ授業デスクに保存</button><button class="secondary" id="save-local-pdf">PDFでローカル保存</button></div><p id="result-message" class="notice" hidden></p></div>`; el('#test-result').innerHTML=html; applyLabels(); }
  function applyLabels(){ document.querySelectorAll('*').forEach(n=>{if(n.childNodes.length===1&&n.firstChild.nodeType===3)n.textContent=n.textContent.replaceAll('AI','');}); document.querySelectorAll('h2').forEach(n=>{n.textContent=n.textContent.replace('ミニテスト生成 MVP','小テスト生成').replace('ワークシート生成 MVP','復習テスト生成');}); document.querySelectorAll('h3').forEach(n=>{n.textContent=n.textContent.replaceAll('ミニテスト','小テスト').replaceAll('ワークシート','復習テスト');}); document.querySelectorAll('button').forEach(n=>{n.textContent=n.textContent.replace('ミニテストを生成','小テストを生成').replace('ワークシートを生成','復習テストを生成');}); }
  function copyText(){
    if(!state.result||!state.result.items){ showMessage('先にミニテストを生成してください。'); return; }
    const text=state.result.items.map((q,i)=>`${i+1}. ${q.question}\n${q.choices?q.choices.join(' / ')+'\n':''}正答：${q.answer}\nやさしい解説：${q.explain}`).join('\n\n');
    const fallback=()=>{ const area=document.createElement('textarea'); area.value=text; area.setAttribute('readonly',''); area.style.position='fixed'; area.style.opacity='0'; document.body.appendChild(area); area.select(); let ok=false; try{ok=document.execCommand('copy');}catch(e){ok=false;} area.remove(); showMessage(ok?'コピーしました。':'コピーできませんでした。問題文を選択してコピーしてください。'); };
    if(navigator.clipboard&&window.isSecureContext){ navigator.clipboard.writeText(text).then(()=>showMessage('コピーしました。')).catch(fallback); } else { fallback(); }
  }
  function printTestPdf(){
    if(!state.result||!state.result.items){ showMessage('先にミニテストを生成してください。'); return; }
    const popup=window.open('', '_blank');
    if(!popup){ showMessage('PDF画面を開けませんでした。ポップアップを許可してください。'); return; }
    const questionCard=q=>`<article class="q ${q.format==='説明問題'?'q-explain':q.format==='短答'?'q-short':'q-choice'}"><div class="qtop"><span class="num">問題${state.result.items.indexOf(q)+1}</span></div><h2>${q.question}</h2>${q.choices?`<div class="choices">${q.choices.map((c,j)=>`<span>${String.fromCharCode(65+j)}　${c}</span>`).join('')}</div>`:''}<div class="work-label">${q.format==='説明問題'?'考え方を書きましょう。':q.format==='短答'?'答えを書きましょう。':'計算・メモ欄'}</div><div class="answer-line"></div></article>`;
    const answerCard=q=>`<article class="a"><div class="qtop"><span class="num">問題${state.result.items.indexOf(q)+1}</span></div><h2>${q.question}</h2><p class="correct"><b>正答</b>　${q.answer}</p><p><b>やさしい解説</b>　${q.explain}</p></article>`;
    const questions=`<div class="columns"><div class="column">${state.result.items.slice(0,3).map(questionCard).join('')}</div><div class="column">${state.result.items.slice(3).map(questionCard).join('')}</div></div>`;
    const answers=`<div class="columns"><div class="column">${state.result.items.slice(0,3).map(answerCard).join('')}</div><div class="column">${state.result.items.slice(3).map(answerCard).join('')}</div></div>`;
    const css='*{box-sizing:border-box}body{margin:0;color:#203040;font-family:-apple-system,BlinkMacSystemFont,"Noto Sans JP","Yu Gothic",sans-serif;line-height:1.7}.sheet{width:257mm;min-height:364mm;margin:0 auto;padding:17mm 19mm;page-break-after:always}header{display:flex;justify-content:space-between;align-items:end;border-bottom:4px solid #8ed0c1;padding-bottom:10px}.meta{font-size:23px;font-weight:700;color:#18324b;letter-spacing:.08em}.unit-meta{font-size:15px;font-weight:700;color:#18324b}.title{display:flex;align-items:center;gap:10px;margin:20px 0 10px}.title span{font-size:30px}.title h1{margin:0;font-size:30px;color:#18324b}.score-box{margin-left:auto;border:2px solid #18324b;border-radius:4px;min-width:42mm;height:14mm;padding:2mm 3mm;font-size:20px;text-align:right;color:#18324b}.score-box span{font-size:12px}.columns{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:12mm;align-items:start}.column{min-width:0}.q,.a{border:2px solid #dbe4ed;border-radius:14px;padding:11px 13px;margin:10px 0;background:#fbfdff;break-inside:avoid;min-height:50mm}.q:nth-child(odd),.a:nth-child(odd){border-color:#bfe5dc;background:#f5fffc}.qtop{display:flex;align-items:center;gap:8px}.num{display:inline-flex;align-items:center;justify-content:center;background:#18324b;color:#fff;border-radius:8px;min-width:27mm;height:9mm;padding:0 5px;font-size:14px;font-weight:800}.q h2,.a h2{font-size:16px;margin:7px 0;color:#203040}.choices{display:grid;grid-template-columns:1fr;gap:6px;margin:8px 0}.choices span{border:1px solid #dbe4ed;border-radius:8px;padding:5px 8px;background:#fff}.work-label{font-size:11px;color:#6b7b8d;margin-top:8px}.answer-line{height:38px;border-bottom:1px dashed #aebdca;margin-top:5px}.q-short .answer-line{height:55px}.q-explain .answer-line{height:82px}.a p{font-size:13px;margin:6px 0}.correct{background:#e8f7f1;border-radius:8px;padding:7px 10px;color:#146c4b}.a b{color:#18324b}@page{size:B4 portrait;margin:0}@media print{.sheet{margin:0}}';
    popup.document.write(`<!doctype html><html lang="ja"><head><meta charset="utf-8"><title>${state.unit} 練習問題</title><style>${css}</style></head><body><section class="sheet"><header><div class="meta">名前：　　　　　　　　　　　　　　　　</div><div class="unit-meta">${state.grade} ${state.subject}「${state.unit}」</div></header><div class="title"><span>✏️</span><h1>練習問題</h1><div class="score-box">　　　<span>点</span></div></div>${questions}</section><section class="sheet"><header><div class="unit-meta">${state.grade} ${state.subject}「${state.unit}」</div></header><div class="title"><span>🌟</span><h1>答え・やさしい解説</h1></div>${answers}</section><script>window.onload=function(){window.print();};<\/script></body></html>`); popup.document.close();
  }
  function buildWorksheet(){
    if(state.grade==='5年'&&state.subject==='算数'&&state.unit==='割合') return [
      {question:'200円の15%はいくらですか。式と答えを書きましょう。',answer:'30円',explain:'200×0.15＝30です。'},
      {question:'80人のうち男子が32人でした。男子は全体の何%ですか。',answer:'40%',explain:'32÷80＝0.4なので40%です。'},
      {question:'定価1,200円の25%引きの値段を求めましょう。',answer:'900円',explain:'25%引きは75%の値段なので、1200×0.75＝900円です。'},
      {question:'もとにする量が60、割合が0.4のとき、比べる量を求めましょう。',answer:'24',explain:'60×0.4＝24です。'},
      {question:'ある数の30%が18です。ある数を求めましょう。',answer:'60',explain:'18÷0.3＝60です。'}
    ];
    return [`${state.unit}で大切な言葉を一つ書きましょう。`,`「${state.unit}」で学んだことを使って答えましょう。`,`答えの理由や考え方を書きましょう。`,'学んだことを図や式で表しましょう。','今日の学習で分かったことを書きましょう。'].map(question=>({question,answer:'',explain:'学習内容を振り返りましょう。'}));
  }
  function renderWorksheetResult(){ if(!state.worksheetResult)return; const card=(q,i)=>`<article class="question"><div class="question-head"><span class="qno">${i+1}</span></div><p><strong>${q.question}</strong></p><p class="answer">正答：${q.answer||'記入内容を確認'}</p><p class="explain">やさしい解説：${q.explain}</p></article>`; el('#worksheet-result').innerHTML=`<div class="result"><h3>${state.grade} ${state.subject}「${state.unit}」ワークシート（${state.level}）</h3>${researchBasis}<div class="worksheet-preview"><div class="worksheet-column">${state.worksheetResult.slice(0,3).map((q,i)=>card(q,i)).join('')}</div><div class="worksheet-column">${state.worksheetResult.slice(3).map((q,i)=>card(q,i+3)).join('')}</div></div><div class="actions"><button class="primary" id="regenerate-worksheet">作り直す</button><button class="secondary" id="copy-worksheet">コピー</button><button class="secondary" id="save-worksheet-desk">マイ授業デスクに保存</button><button class="secondary" id="save-worksheet-pdf">PDFでローカル保存</button></div><p id="worksheet-message" class="notice" hidden></p></div>`; applyLabels(); }
  function copyWorksheet(){ const text=state.worksheetResult.map((q,i)=>`問題${i+1}：${q.question}\n正答：${q.answer}\nやさしい解説：${q.explain}`).join('\n\n'); navigator.clipboard?.writeText(text).then(()=>{const n=el('#worksheet-message');n.hidden=false;n.textContent='コピーしました。';}).catch(()=>{const n=el('#worksheet-message');n.hidden=false;n.textContent='コピーできませんでした。問題文を選択してコピーしてください。';}); }
  function saveWorksheetToDesk(){ try{const key='schoolpilot-review-tests';const all=JSON.parse(localStorage.getItem(key)||'[]').filter(x=>!(x.grade===state.grade&&x.subject===state.subject&&x.unit===state.unit&&x.level===state.level));all.unshift({grade:state.grade,subject:state.subject,unit:state.unit,level:state.level,items:state.worksheetResult,savedAt:new Date().toISOString()});localStorage.setItem(key,JSON.stringify(all.slice(0,20)));const n=el('#worksheet-message');if(n){n.hidden=false;n.textContent='マイ授業デスクに保存しました。';}}catch(e){const n=el('#worksheet-message');if(n){n.hidden=false;n.textContent='保存できませんでした。';}} }
  function renderPackSection(){ if(state.page!=='detail'||state.activeTab!=='test'||!el('.panel')||el('#pack-result'))return; const box=document.createElement('div'); box.className='feature pack'; box.innerHTML='<h2>授業パック生成</h2><p>この単元の授業準備に必要な素材を、まとめて一度に用意します。</p><div class="actions"><button class="primary" id="generate-pack">授業パックを準備</button></div><div id="pack-result"></div>'; el('.panel').appendChild(box); }
  function renderPackResult(){ const node=el('#pack-result'); if(!node)return; node.innerHTML=`<div class="pack-list"><div><b>授業案</b><span>45分の流れ・発問・つまずき対応</span></div><div><b>板書案</b><span>導入からまとめまでの板書ポイント</span></div><div><b>小テスト</b><span>${state.result.items.length}問・正答と解説つき</span></div><div><b>復習テスト</b><span>${state.worksheetResult.length}問・記入欄つき</span></div></div><p class="notice">4つの素材を同じ単元・${state.level}の条件で準備しました。各機能のボタンから内容を確認できます。</p>`; }
  function renderSupportResult(type){ const isBoard=type==='board'; const title=isBoard?'板書例':'指導案・授業展開例'; const content=isBoard?['めあて：割合の求め方を考えよう','問題：120円の20%はいくら？','数直線で「もとにする量」と「比べられる量」を確認','割合＝比べられる量÷もとにする量','まとめ：割合は、もとにする量を1とみたときの比']:[]; const lesson=['導入 5分：身近な割合の場面を提示','問題提示 5分：何を1とみるか考える','個人思考 10分：数直線と式で表す','交流 15分：考え方を比べる','まとめ 5分：公式と言葉を整理','振り返り 5分：分かったことを書く']; const rows=isBoard?content:lesson; const box=el('.panel'); if(!box)return; let old=el('#support-result'); if(!old){old=document.createElement('div');old.id='support-result';old.className='support-result';box.appendChild(old);} old.innerHTML=`<div class="result"><h3>${state.grade} ${state.subject}「${state.unit}」${title}</h3><div class="support-paper">${rows.map((x,i)=>`<div class="support-row"><b>${i+1}</b><span>${x}</span></div>`).join('')}</div><div class="actions"><button class="primary" id="print-support" data-support-type="${type}">印刷</button><button class="secondary" id="save-support" data-support-type="${type}">マイ授業デスクに保存</button></div></div>`; }
  function addBoardVisual(){ const paper=el('#support-result .support-paper'); if(!paper||el('#board-visual'))return; paper.insertAdjacentHTML('beforebegin','<div id="board-visual" class="board-visual"><div class="board-head">黒板イメージ</div><div class="board-columns"><div class="board-part"><span class="board-icon">🎯</span><b>めあて</b><p>割合の求め方を考えよう</p></div><div class="board-part"><span class="board-icon">🏀</span><b>問題</b><p>120円の20%は？</p><div class="number-line"><span>0</span><i></i><span>1</span></div></div><div class="board-part"><span class="board-icon">🧮</span><b>まとめ</b><p>割合＝比べられる量÷もとにする量</p></div></div></div>'); }
  function saveSupport(type){ const node=el('#support-result'); if(!node)return; const rows=Array.from(node.querySelectorAll('.support-row')).map(r=>r.querySelector('span').textContent); try{const key='schoolpilot-support-materials';const all=JSON.parse(localStorage.getItem(key)||'[]');all.unshift({grade:state.grade,subject:state.subject,unit:state.unit,level:state.level,type,title:node.querySelector('h3').textContent,rows,savedAt:new Date().toISOString()});localStorage.setItem(key,JSON.stringify(all.slice(0,20)));node.querySelector('.result').insertAdjacentHTML('beforeend','<p class="notice">マイ授業デスクに保存しました。</p>');}catch(e){} }
  function printSupport(){ const node=el('#support-result'); if(!node)return; const popup=window.open('','_blank'); if(!popup)return; popup.document.write(`<html lang="ja"><head><meta charset="utf-8"><title>${state.unit} 授業準備</title><style>@page{size:A4 portrait;margin:0}body{font-family:"Yu Gothic",sans-serif;padding:18mm;color:#203040}h1{font-size:25px;border-bottom:3px solid #8ed0c1;padding-bottom:10px}.meta{font-size:14px;color:#526576;margin-bottom:16px}.row{border:1px solid #bfe5dc;border-radius:10px;padding:13px;margin:10px 0;display:flex;gap:12px;min-height:22mm}.row b{background:#18324b;color:#fff;border-radius:50%;width:28px;height:28px;text-align:center;padding-top:2px}.row span{font-size:16px;font-weight:700}</style></head><body><h1>${state.subject}「${state.unit}」${node.querySelector('h3').textContent.split('」')[1]||''}</h1><div class="meta">${state.grade} / 授業レベル：${state.level}</div>${Array.from(node.querySelectorAll('.support-row')).map(r=>`<div class="row"><b>${r.querySelector('b').textContent}</b><span>${r.querySelector('span').textContent}</span></div>`).join('')}<script>window.onload=function(){window.print();};<\/script></body></html>`); popup.document.close(); }
  function printWorksheet(){ const popup=window.open('','_blank'); if(!popup)return; const card=(q,i)=>`<article><b>問題${i+1}</b><p>${q}</p><div></div></article>`; const left=state.worksheetResult.slice(0,3).map((q,i)=>card(q,i)).join(''); const right=state.worksheetResult.slice(3).map((q,i)=>card(q,i+3)).join(''); const answerItems=buildItems(); const answerCard=(q,i)=>`<article class="answer"><b>問題${i+1}</b><p><strong>正答：</strong>${q.answer}</p><p class="explain">${q.explain}</p></article>`; const answerLeft=answerItems.slice(0,3).map((q,i)=>answerCard(q,i)).join(''); const answerRight=answerItems.slice(3).map((q,i)=>answerCard(q,i+3)).join(''); popup.document.write(`<html lang="ja"><head><meta charset="utf-8"><title>復習テスト</title><style>@page{size:B4 portrait;margin:0}body{font-family:"Yu Gothic",sans-serif;padding:18mm;color:#203040}h1{font-size:28px;border-bottom:3px solid #8ed0c1;padding-bottom:10px}header{font-size:22px;margin-bottom:15px}main{display:grid;grid-template-columns:1fr 1fr;gap:12mm;align-items:start}.column{min-width:0}article{border:2px solid #bfe5dc;border-radius:14px;padding:14px;margin:0 0 12px;min-height:48mm;break-inside:avoid}article:nth-child(even){border-color:#f5d7a9}article b{display:inline-block;background:#18324b;color:#fff;border-radius:7px;padding:3px 9px}article p{font-size:18px;font-weight:700}article div{height:40px;border-bottom:1px dashed #aebdca;margin-top:16px}.answers{page-break-before:always}.answer{min-height:35mm}.answer p{font-size:15px;font-weight:400}.answer .explain{font-size:13px;color:#526576}</style></head><body><header>名前：　　　　　　　　　　　　　　${state.grade} ${state.subject}「${state.unit}」</header><h1>復習テスト</h1><main><div class="column">${left}</div><div class="column">${right}</div></main><section class="answers"><h1>復習テスト　回答・解説</h1><main><div class="column">${answerLeft}</div><div class="column">${answerRight}</div></main></section><script>window.onload=function(){window.print();};<\/script></body></html>`); popup.document.close(); }
  function printWorksheet(){ const popup=window.open('','_blank'); if(!popup)return; const card=(q,i)=>`<article><b>問題${i+1}</b><p>${q.question}</p><div></div></article>`; const left=state.worksheetResult.slice(0,3).map((q,i)=>card(q,i)).join(''); const right=state.worksheetResult.slice(3).map((q,i)=>card(q,i+3)).join(''); const answerCard=(q,i)=>`<article class="answer"><b>問題${i+1}</b><p><strong>正答：</strong>${q.answer||'記入内容を確認'}</p><p class="explain">${q.explain}</p></article>`; const answerLeft=state.worksheetResult.slice(0,3).map((q,i)=>answerCard(q,i)).join(''); const answerRight=state.worksheetResult.slice(3).map((q,i)=>answerCard(q,i+3)).join(''); popup.document.write(`<html lang="ja"><head><meta charset="utf-8"><title>復習テスト</title><style>@page{size:B4 portrait;margin:0}body{font-family:"Yu Gothic",sans-serif;padding:18mm;color:#203040}h1{font-size:28px;border-bottom:3px solid #8ed0c1;padding-bottom:10px}header{font-size:22px;margin-bottom:15px;display:flex;justify-content:space-between}.score{border:2px solid #18324b;padding:5px 20px;font-size:15px}main{display:grid;grid-template-columns:1fr 1fr;gap:12mm;align-items:start}.column{min-width:0}article{border:2px solid #bfe5dc;border-radius:14px;padding:14px;margin:0 0 12px;min-height:48mm;break-inside:avoid}article:nth-child(even){border-color:#f5d7a9}article b{display:inline-block;background:#18324b;color:#fff;border-radius:7px;padding:3px 9px}article p{font-size:18px;font-weight:700}article div{height:40px;border-bottom:1px dashed #aebdca;margin-top:16px}.answers{page-break-before:always}.answer{min-height:35mm}.answer p{font-size:15px;font-weight:400}.answer .explain{font-size:13px;color:#526576}</style></head><body><header><span>名前：　　　　　　　　　　　　　　${state.grade} ${state.subject}「${state.unit}」</span><span class="score">　　　点</span></header><h1>復習テスト</h1><main><div class="column">${left}</div><div class="column">${right}</div></main><section class="answers"><h1>復習テスト　回答・解説</h1><main><div class="column">${answerLeft}</div><div class="column">${answerRight}</div></main></section><script>window.onload=function(){window.print();};<\/script></body></html>`); popup.document.close(); }
  function showMessage(msg){ const node=el('#result-message'); if(node){node.hidden=false;node.textContent=msg;} }
  function render(){ state.page==='home'?renderHome():state.page==='desk'?renderDesk():renderDetail(); renderPackSection(); renderSupportDesk(); applyLabels(); }
  document.addEventListener('click', e=>{ const t=e.target.closest('button'); if(!t)return; if(t.dataset.page){state.page=t.dataset.page;document.querySelectorAll('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.page===state.page));render();return;} if(t.dataset.grade){state.grade=t.dataset.grade;state.unit=selectedUnits()[0]||units[state.subject][0];render();return;} if(t.dataset.subject){state.subject=t.dataset.subject;state.unit=selectedUnits()[0]||units[state.subject][0];render();return;} if(t.dataset.unit){state.unit=t.dataset.unit;state.page='detail';render();return;} if(t.dataset.level){state.level=t.dataset.level;render();return;} if(t.dataset.demo){renderSupportResult(t.dataset.demo);return;} if(t.id==='generate-test'||t.id==='regenerate-test'){state.result={items:buildItems()};renderTestResult();return;} if(t.id==='generate-worksheet'||t.id==='regenerate-worksheet'){state.worksheetResult=buildWorksheet();renderWorksheetResult();applyLabels();return;} if(t.id==='generate-pack'){state.result={items:buildItems()};state.worksheetResult=buildWorksheet();renderPackResult();return;} if(t.id==='print-support'){printSupport();return;} if(t.id==='save-support'){saveSupport(t.dataset.supportType);return;} if(t.id==='delete-support'){const items=loadSupportSaved();items.splice(Number(t.dataset.deleteSupport),1);localStorage.setItem('schoolpilot-support-materials',JSON.stringify(items));render();return;} if(t.id==='copy-test'){copyText();return;} if(t.id==='copy-worksheet'){copyWorksheet();return;} if(t.id==='print-worksheet'||t.id==='save-worksheet-pdf'){printWorksheet();return;} if(t.id==='save-worksheet-desk'){saveWorksheetToDesk();return;} if(t.dataset.renameSaved){renameSaved(t.dataset.renameStore,Number(t.dataset.renameSaved));return;} if(t.dataset.deleteSaved){deleteSaved(t.dataset.deleteStore,Number(t.dataset.deleteSaved));return;} if(t.id==='save-desk'){if(saveToDesk())showMessage('マイ授業デスクに保存しました。');return;} if(t.id==='save-local-pdf'){printTestPdf();return;} if(t.dataset.openSaved){const x=loadSaved().concat(loadReviewSaved())[Number(t.dataset.openSaved)];if(x){Object.assign(state,x,{page:'detail'});render();state.result={items:x.items};renderTestResult();}} });
  document.addEventListener('click', e=>{ const t=e.target.closest('[data-publisher]'); if(!t)return; state.publisher=t.dataset.publisher; state.unit=selectedUnits()[0]||units[state.subject][0]; render(); });
  document.addEventListener('click', e=>{ const t=e.target.closest('[data-search]'); if(!t||t.disabled)return; state.page='detail'; state.activeTab='overview'; render(); });
  document.addEventListener('click',e=>{const t=e.target.closest('[data-delete-support]');if(!t)return;const items=loadSupportSaved();items.splice(Number(t.dataset.deleteSupport),1);localStorage.setItem('schoolpilot-support-materials',JSON.stringify(items));render();});
  document.addEventListener('click',e=>{const t=e.target.closest('[data-demo="board"]');if(t){setTimeout(addBoardVisual,0);}});
  document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){state.activeTab=tab.dataset.tab;renderActiveTab();renderPackSection();return;}const minutes=e.target.closest('[data-minutes]');if(minutes){state.lessonMinutes=Number(minutes.dataset.minutes);renderActiveTab();}});
  document.addEventListener('click',e=>{const lesson=e.target.closest('[data-demo="lesson"]');if(lesson){setTimeout(()=>{const rows=document.querySelectorAll('#support-result .support-row');const count=state.lessonMinutes===15?3:state.lessonMinutes===30?5:6;rows.forEach((r,i)=>{if(i>=count)r.remove();});},0);}});
  render();
})();
